# Generated by Django 4.2.30 on 2026-04-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_initial'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('equipment_number', models.CharField(max_length=100, unique=True, verbose_name='رقم المعدة')),
                ('category', models.CharField(choices=[('machinery', 'آلات'), ('vehicle', 'مركبات'), ('electrical', 'كهربائية'), ('plumbing', 'سباكة'), ('hvac', 'تكييف وتبريد'), ('safety', 'سلامة'), ('other', 'أخرى')], max_length=20, verbose_name='التصنيف')),
                ('brand', models.CharField(blank=True, max_length=200, verbose_name='العلامة التجارية')),
                ('model_number', models.CharField(blank=True, max_length=200, verbose_name='رقم الموديل')),
                ('serial_number', models.CharField(blank=True, max_length=200, verbose_name='الرقم التسلسلي')),
                ('location', models.TextField(verbose_name='الموقع')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشراء')),
                ('purchase_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الشراء')),
                ('warranty_end', models.DateField(blank=True, null=True, verbose_name='انتهاء الضمان')),
                ('status', models.CharField(choices=[('operational', 'تعمل'), ('maintenance', 'صيانة'), ('broken', 'معطلة'), ('retired', 'متقاعدة')], db_index=True, default='operational', max_length=20, verbose_name='الحالة')),
                ('current_meter_reading', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='قراءة العداد الحالية')),
                ('image', models.ImageField(blank=True, upload_to='equipment/', verbose_name='صورة المعدة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم المكلف')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسؤول الصيانة')),
            ],
            options={
                'verbose_name': 'المعدة',
                'verbose_name_plural': 'المعدات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'وقائية'), ('corrective', 'تصحيحية'), ('emergency', 'طوارئ'), ('inspection', 'فحص')], max_length=20, verbose_name='نوع الصيانة')),
                ('frequency_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع التكرار')),
                ('frequency_value', models.IntegerField(default=1, help_text='عدد الوحدات (أيام/أسابيع/أشهر)', verbose_name='قيمة التكرار')),
                ('last_performed', models.DateField(blank=True, null=True, verbose_name='آخر تنفيذ')),
                ('next_due', models.DateField(verbose_name='تاريخ الاستحقاق التالي')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة المقدرة')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الساعات المقدرة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='equipmaint.equipment', verbose_name='المعدة')),
            ],
            options={
                'verbose_name': 'جدول الصيانة',
                'verbose_name_plural': 'جداول الصيانة',
                'ordering': ['next_due'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_order_number', models.CharField(max_length=100, unique=True, verbose_name='رقم أمر العمل')),
                ('work_type', models.CharField(choices=[('preventive', 'وقائية'), ('corrective', 'تصحيحية'), ('emergency', 'طوارئ'), ('inspection', 'فحص')], max_length=20, verbose_name='نوع العمل')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], default='medium', max_length=20, verbose_name='الأولوية')),
                ('status', models.CharField(choices=[('requested', 'مطلوب'), ('approved', 'موافق عليه'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='requested', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة الفعلية')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='الساعات الفعلية')),
                ('parts_used', models.TextField(blank=True, default='', verbose_name='القطع المستخدمة')),
                ('completion_notes', models.TextField(blank=True, default='', verbose_name='ملاحظات الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_approvals', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_assignments', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول عن التنفيذ')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='equipmaint.equipment', verbose_name='المعدة')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_requests', to=settings.AUTH_USER_MODEL, verbose_name='مقدم الطلب')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='equipmaint.maintenanceschedule', verbose_name='جدول الصيانة')),
            ],
            options={
                'verbose_name': 'أمر عمل صيانة',
                'verbose_name_plural': 'أوامر عمل الصيانة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenancePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255, verbose_name='اسم القطعة')),
                ('part_number', models.CharField(blank=True, max_length=200, verbose_name='رقم القطعة')),
                ('quantity', models.IntegerField(default=1, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الوحدة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchases.supplier', verbose_name='المورد')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='equipmaint.maintenanceworkorder', verbose_name='أمر العمل')),
            ],
            options={
                'verbose_name': 'قطعة غيار',
                'verbose_name_plural': 'قطع الغيار',
                'ordering': ['part_name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري'), ('annual', 'سنوي'), ('special', 'خاص')], max_length=20, verbose_name='نوع الفحص')),
                ('inspection_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الفحص')),
                ('condition_rating', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('fair', 'مقبول'), ('poor', 'ضعيف'), ('critical', 'حرج')], max_length=20, verbose_name='تقييم الحالة')),
                ('findings', models.TextField(blank=True, default='', verbose_name='الملاحظات')),
                ('recommendations', models.TextField(blank=True, default='', verbose_name='التوصيات')),
                ('next_inspection', models.DateField(blank=True, null=True, verbose_name='تاريخ الفحص التالي')),
                ('status', models.CharField(choices=[('pass', 'ناجح'), ('conditional_pass', 'ناجح بشروط'), ('fail', 'فاشل')], default='pass', max_length=20, verbose_name='النتيجة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipmaint.equipment', verbose_name='المعدة')),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المفتش')),
            ],
            options={
                'verbose_name': 'فحص المعدة',
                'verbose_name_plural': 'فحوصات المعدات',
                'ordering': ['-inspection_date'],
            },
        ),
    ]
