# Generated by Django 6.0.4 on 2026-04-18 17:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('purchases', '0001_initial'),
        ('sales', '0003_alter_salesorder_order_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('order_date', models.DateField(verbose_name='تاريخ الأمر')),
                ('ship_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الشحن')),
                ('port_of_loading', models.CharField(max_length=200, verbose_name='ميناء التحميل')),
                ('destination_country', models.CharField(max_length=200, verbose_name='بلد الوجهة')),
                ('destination_port', models.CharField(max_length=200, verbose_name='ميناء الوجهة')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, verbose_name='سعر الصرف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('packed', 'معبأ'), ('customs', 'جمارك'), ('shipped', 'مشحون'), ('delivered', 'مسلّم'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي المبلغ')),
                ('shipping_terms', models.CharField(blank=True, default='', max_length=100, verbose_name='شروط الشحن')),
                ('payment_terms', models.TextField(blank=True, default='', verbose_name='شروط الدفع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_orders', to='sales.customer', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'أمر تصدير',
                'verbose_name_plural': 'أوامر التصدير',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('hs_code', models.CharField(blank=True, default='', max_length=50, verbose_name='رمز النظام المنسق')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='إجمالي السعر')),
                ('unit', models.CharField(default='piece', max_length=50, verbose_name='الوحدة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_items', to='inventory.product', verbose_name='المنتج')),
                ('export_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='importexport.exportorder', verbose_name='أمر التصدير')),
            ],
            options={
                'verbose_name': 'بند تصدير',
                'verbose_name_plural': 'بنود التصدير',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ImportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('order_date', models.DateField(verbose_name='تاريخ الأمر')),
                ('expected_arrival', models.DateField(blank=True, null=True, verbose_name='تاريخ الوصول المتوقع')),
                ('actual_arrival', models.DateField(blank=True, null=True, verbose_name='تاريخ الوصول الفعلي')),
                ('port_of_entry', models.CharField(max_length=200, verbose_name='ميناء الدخول')),
                ('country_of_origin', models.CharField(max_length=200, verbose_name='بلد المنشأ')),
                ('currency', models.CharField(default='USD', max_length=10, verbose_name='العملة')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10, verbose_name='سعر الصرف')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('customs', 'جمارك'), ('transit', 'عبور'), ('warehouse', 'مستودع'), ('customs_hold', 'احتجاز جمركي'), ('received', 'مستلم'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي المبلغ')),
                ('customs_duties', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='الرسوم الجمركية')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='تكلفة الشحن')),
                ('insurance_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='تكلفة التأمين')),
                ('other_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='تكاليف أخرى')),
                ('total_landed_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي التكلفة الواردة')),
                ('payment_terms', models.TextField(blank=True, default='', verbose_name='شروط الدفع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_orders_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_orders', to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'أمر استيراد',
                'verbose_name_plural': 'أوامر الاستيراد',
                'ordering': ['-order_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('hs_code', models.CharField(blank=True, default='', max_length=50, verbose_name='رمز النظام المنسق')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='إجمالي السعر')),
                ('customs_duty_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='نسبة الرسوم الجمركية')),
                ('customs_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الرسوم الجمركية')),
                ('unit', models.CharField(default='piece', max_length=50, verbose_name='الوحدة')),
                ('country_of_origin', models.CharField(blank=True, default='', max_length=200, verbose_name='بلد المنشأ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_items', to='inventory.product', verbose_name='المنتج')),
                ('import_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='importexport.importorder', verbose_name='أمر الاستيراد')),
            ],
            options={
                'verbose_name': 'بند استيراد',
                'verbose_name_plural': 'بنود الاستيراد',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomsDeclaration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('declaration_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإقرار')),
                ('declaration_type', models.CharField(choices=[('import', 'استيراد'), ('export', 'تصدير'), ('transit', 'عبور')], max_length=20, verbose_name='نوع الإقرار')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('submitted', 'مقدم'), ('cleared', 'مخلى'), ('hold', 'معلق'), ('rejected', 'مرفوض')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('submitted_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التقديم')),
                ('cleared_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التخليص')),
                ('declared_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='القيمة المصرّح بها')),
                ('duties_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الرسوم')),
                ('taxes_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='مبلغ الضرائب')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_declarations_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('export_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_declarations', to='importexport.exportorder', verbose_name='أمر التصدير')),
                ('import_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customs_declarations', to='importexport.importorder', verbose_name='أمر الاستيراد')),
            ],
            options={
                'verbose_name': 'إقرار جمركي',
                'verbose_name_plural': 'الإقرارات الجمركية',
                'ordering': ['-created_at'],
            },
        ),
    ]
