# Generated by Django 4.2.30 on 2026-04-13 13:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المورد')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم المورد (إنجليزي)')),
                ('contact_person', models.CharField(blank=True, default='', max_length=255, verbose_name='جهة الاتصال')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, default='', verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, default='', max_length=50, verbose_name='الرقم الضريبي')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مورد',
                'verbose_name_plural': 'الموردون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('received', 'مستلم'), ('partial', 'استلام جزئي'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('order_date', models.DateField(db_index=True, default=datetime.date.today, verbose_name='تاريخ الأمر')),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستلام المتوقع')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'أمر شراء',
                'verbose_name_plural': 'أوامر الشراء',
                'ordering': ['-created_at'],
                'permissions': [('confirm_order', 'Can confirm purchase orders'), ('cancel_order', 'Can cancel purchase orders'), ('change_status', 'Can change order status')],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='السعر عند إنشاء الأمر', max_digits=12, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الإجمالي الفرعي')),
                ('received_quantity', models.PositiveIntegerField(default=0, verbose_name='الكمية المستلمة')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaseorder', verbose_name='أمر الشراء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_items', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند أمر شراء',
                'verbose_name_plural': 'بنود أوامر الشراء',
                'unique_together': {('order', 'product')},
            },
        ),
    ]
