# Generated by Django 4.2.30 on 2026-04-28 15:45
# Rewritten: removed inventory dependency, replaced product FK with product_name

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0003_shift_department_parent_employeeshift_and_more'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisition_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الطلب')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'بانتظار الموافقة'), ('approved', 'موصوف'), ('rejected', 'مرفوض'), ('converted_to_po', 'تم التحويل لأمر شراء')], db_index=True, default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=500)),
                ('required_date', models.DateField(blank=True, null=True, verbose_name='التاريخ المطلوب')),
                ('estimated_budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الميزانية المقدرة')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requisitions', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requisitions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'طلب شراء',
                'verbose_name_plural': 'طلبات الشراء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRequisitionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='سعر الوحدة المقدر')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المجموع')),
                ('notes', models.TextField(blank=True)),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.purchaserequisition')),
            ],
            options={
                'verbose_name': 'بند طلب شراء',
                'verbose_name_plural': 'بنود طلبات الشراء',
            },
        ),
    ]
