# Generated by Django 4.2 on 2026-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_alter_purchaserequisition_requested_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisition',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
    ]
