# Generated by Django 4.2.30 on 2026-04-15 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربية')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('icon', models.CharField(default='Video', help_text='اسم أيقونة من lucide-react مثل: Video, BookOpen, Settings', max_length=50, verbose_name='أيقونة اللوسيد')),
                ('color', models.CharField(default='#3B82F6', help_text='كود اللون HEX مثل: #3B82F6', max_length=7, verbose_name='اللون')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف فيديو',
                'verbose_name_plural': 'تصنيفات الفيديوهات',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VideoInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(max_length=200, verbose_name='العنوان بالعربية')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='العنوان بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, verbose_name='الوصف بالعربية')),
                ('description_en', models.TextField(blank=True, verbose_name='الوصف بالإنجليزية')),
                ('video_file', models.FileField(blank=True, help_text='ارفع ملف فيديو بتنسيق MP4, WebM, أو OGG', null=True, upload_to='videos/%Y/%m/', verbose_name='ملف الفيديو')),
                ('video_url', models.URLField(blank=True, help_text='رابط فيديو من YouTube, Vimeo, أو أي مصدر خارجي', verbose_name='رابط الفيديو الخارجي')),
                ('duration_seconds', models.IntegerField(default=0, help_text='مدة الفيديو بالثواني', verbose_name='المدة بالثواني')),
                ('thumbnail', models.ImageField(blank=True, help_text='صورة مصغرة للفيديو (يوصى بأبعاد 16:9)', null=True, upload_to='videos/thumbnails/%Y/%m/', verbose_name='صورة مصغرة')),
                ('category', models.CharField(choices=[('getting_started', 'البدء مع النظام'), ('inventory', 'إدارة المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('documents', 'المستندات'), ('projects', 'المشاريع'), ('reports', 'التقارير'), ('settings', 'الإعدادات'), ('advanced', 'متقدم'), ('troubleshooting', 'حل المشكلات')], db_index=True, default='getting_started', max_length=30, verbose_name='التصنيف')),
                ('tags', models.JSONField(blank=True, default=list, help_text='قائمة بالكلمات المفتاحية للبحث', verbose_name='الكلمات المفتاحية')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميز')),
                ('difficulty_level', models.CharField(choices=[('beginner', 'مبتدئ'), ('intermediate', 'متوسط'), ('advanced', 'متقدم')], default='beginner', max_length=20, verbose_name='مستوى الصعوبة')),
                ('views_count', models.IntegerField(default=0, verbose_name='عدد المشاهدات')),
                ('likes_count', models.IntegerField(default=0, verbose_name='عدد الإعجابات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='videos.videocategory', verbose_name='التصنيف المخصص')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_videos', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'فيديو تعليمي',
                'verbose_name_plural': 'الفيديوهات التعليمية',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='التعليق')),
                ('timestamp_seconds', models.IntegerField(default=0, help_text='التوقيت في الفيديو الذي يشير إليه التعليق', verbose_name='التوقيت بالثواني')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='مثبّت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='videos.videoinstruction', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'تعليق فيديو',
                'verbose_name_plural': 'تعليقات الفيديوهات',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_seconds', models.IntegerField(default=0, verbose_name='الثواني المشاهدة')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('last_watched_at', models.DateTimeField(auto_now=True, verbose_name='آخر مشاهدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='videos.videoinstruction', verbose_name='الفيديو')),
            ],
            options={
                'verbose_name': 'تقدم مشاهدة',
                'verbose_name_plural': 'تقدم المشاهدة',
                'ordering': ['-last_watched_at'],
                'unique_together': {('user', 'video')},
            },
        ),
        migrations.AddIndex(
            model_name='videoinstruction',
            index=models.Index(fields=['category', 'is_active'], name='videos_vide_categor_634580_idx'),
        ),
        migrations.AddIndex(
            model_name='videoinstruction',
            index=models.Index(fields=['is_featured', 'is_active'], name='videos_vide_is_feat_9e68d6_idx'),
        ),
    ]
