# Generated by Django 4.2.30 on 2026-04-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('hr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='اسم التصنيف')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم التصنيف (إنجليزي)')),
                ('useful_life_years', models.IntegerField(default=5, verbose_name='سنوات العمر الافتراضي')),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'القسط الثابت'), ('declining_balance', 'القسط المتناقص')], default='straight_line', max_length=20, verbose_name='طريقة الإهلاك')),
                ('salvage_value_rate', models.DecimalField(decimal_places=2, default=0, help_text='النسبة المئوية من سعر الشراء كقيمة تخريدية', max_digits=5, verbose_name='نسبة القيمة التخريدية')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'تصنيف أصل',
                'verbose_name_plural': 'تصنيفات الأصول',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم الأصل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الأصل')),
                ('name_en', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم الأصل (إنجليزي)')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='الرقم التسلسلي')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='الباركود')),
                ('purchase_date', models.DateField(verbose_name='تاريخ الشراء')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الشراء')),
                ('salvage_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='القيمة التخريدية')),
                ('useful_life_months', models.IntegerField(verbose_name='العمر الافتراضي (بالشهور)')),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مجمع الإهلاك')),
                ('location', models.CharField(blank=True, default='', max_length=200, verbose_name='الموقع')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الضمان')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('in_maintenance', 'في الصيانة'), ('disposed', 'مخرد'), ('sold', 'مباع'), ('lost', 'مفقود')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='hr.employee', verbose_name='مسند إلى')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='assets.assetcategory', verbose_name='التصنيف')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_assets', to='hr.department', verbose_name='القسم')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_assets', to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'أصل ثابت',
                'verbose_name_plural': 'الأصول الثابتة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_location', models.CharField(blank=True, default='', max_length=200, verbose_name='من موقع')),
                ('to_location', models.CharField(blank=True, default='', max_length=200, verbose_name='إلى موقع')),
                ('transfer_date', models.DateField(verbose_name='تاريخ النقل')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='assets.fixedasset', verbose_name='الأصل')),
                ('from_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_out', to='hr.department', verbose_name='من قسم')),
                ('from_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_out', to='hr.employee', verbose_name='من موظف')),
                ('to_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_in', to='hr.department', verbose_name='إلى قسم')),
                ('to_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_transfers_in', to='hr.employee', verbose_name='إلى موظف')),
            ],
            options={
                'verbose_name': 'نقل أصل',
                'verbose_name_plural': 'نقل الأصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'وقائية'), ('corrective', 'تصحيحية'), ('emergency', 'طارئة')], max_length=20, verbose_name='نوع الصيانة')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة')),
                ('maintenance_date', models.DateField(verbose_name='تاريخ الصيانة')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصيانة القادمة')),
                ('vendor', models.CharField(blank=True, default='', max_length=200, verbose_name='مزود الخدمة')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='scheduled', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='assets.fixedasset', verbose_name='الأصل')),
            ],
            options={
                'verbose_name': 'صيانة أصل',
                'verbose_name_plural': 'صيانات الأصول',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssetDisposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposal_type', models.CharField(choices=[('sold', 'مباع'), ('scraped', 'مخرد'), ('donated', 'متبرع به'), ('lost', 'مفقود')], max_length=20, verbose_name='نوع التخريد')),
                ('disposal_date', models.DateField(verbose_name='تاريخ التخريد')),
                ('disposal_value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='قيمة التخريد')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم المشتري')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disposals', to='assets.fixedasset', verbose_name='الأصل')),
            ],
            options={
                'verbose_name': 'تخريد أصل',
                'verbose_name_plural': 'تخريد الأصول',
                'ordering': ['-created_at'],
            },
        ),
    ]
