# Generated by Django 4.2.30 on 2026-04-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttask',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الساعات الفعلية'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='depends_on',
            field=models.ManyToManyField(blank=True, related_name='blocks', to='projects.projecttask', verbose_name='يعتمد على'),
        ),
        migrations.AddField(
            model_name='projecttask',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='الساعات المقدرة'),
        ),
    ]
