# Generated by Django 6.0.4 on 2026-05-01 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_projecttask_actual_hours_projecttask_depends_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectexpense',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='التاريخ'),
        ),
    ]
