# Generated by Django 4.2 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0005_remove_salesorder_sales_order_status_date_idx'),
        ('projects', '0003_alter_projectexpense_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='عدد الساعات')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('billable', models.BooleanField(default=True, verbose_name='قابل للفوترة')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='معدل الساعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projects.project', verbose_name='المشروع')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_entries', to='projects.projecttask', verbose_name='المهمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_time_entries', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل وقت',
                'verbose_name_plural': 'سجلات الوقت',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectRisk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_name', models.CharField(max_length=255, verbose_name='اسم الخطر')),
                ('category', models.CharField(choices=[('financial', 'مالي'), ('operational', 'تشغيلي'), ('technical', 'تقني'), ('regulatory', 'تنظيمي'), ('environmental', 'بيئي'), ('schedule', 'جدول زمني'), ('resource', 'موارد')], db_index=True, max_length=20, verbose_name='الفئة')),
                ('probability', models.PositiveIntegerField(help_text='من 1 (منخفض) إلى 5 (مرتفع)', verbose_name='احتمالية الحدوث')),
                ('impact', models.PositiveIntegerField(help_text='من 1 (منخفض) إلى 5 (مرتفع)', verbose_name='درجة التأثير')),
                ('status', models.CharField(choices=[('identified', 'محدد'), ('analyzing', 'قيد التحليل'), ('mitigating', 'قيد التخفيف'), ('occurred', 'وقع'), ('closed', 'مغلق'), ('accepted', 'مقبول')], db_index=True, default='identified', max_length=20, verbose_name='الحالة')),
                ('response_strategy', models.CharField(blank=True, choices=[('avoid', 'تجنب'), ('mitigate', 'تخفيف'), ('transfer', 'نقل'), ('accept', 'قبول')], default='', max_length=20, verbose_name='استراتيجية الاستجابة')),
                ('response_plan', models.TextField(blank=True, default='', verbose_name='خطة الاستجابة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_risks', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risks', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'خطر مشروع',
                'verbose_name_plural': 'مخاطر المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المرحلة')),
                ('phase_type', models.CharField(choices=[('planning', 'تخطيط'), ('design', 'تصميم'), ('development', 'تطوير'), ('testing', 'اختبار'), ('deployment', 'نشر'), ('closure', 'إغلاق'), ('sprint', 'سبرنت')], max_length=20, verbose_name='نوع المرحلة')),
                ('status', models.CharField(choices=[('not_started', 'لم يبدأ'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('delayed', 'متأخر')], db_index=True, default='not_started', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('progress', models.PositiveIntegerField(default=0, help_text='من 0 إلى 100', verbose_name='نسبة الإنجاز %')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='ترتيب')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مرحلة مشروع',
                'verbose_name_plural': 'مراحل المشاريع',
                'ordering': ['order', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المعلم')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('achieved', 'تم التحقيق'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='projects.projectphase', verbose_name='المرحلة')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'معلم مشروع',
                'verbose_name_plural': 'معالم المشاريع',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('doc_type', models.CharField(choices=[('contract', 'عقد'), ('specification', 'مواصفات'), ('drawing', 'رسم'), ('correspondence', 'مراسلات'), ('report', 'تقرير'), ('invoice', 'فاتورة'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='نوع المستند')),
                ('file', models.FileField(upload_to='project_documents/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='الإصدار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project', verbose_name='المشروع')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_project_documents', to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مستند مشروع',
                'verbose_name_plural': 'مستندات المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='رقم العقد')),
                ('contract_type', models.CharField(choices=[('fixed_price', 'سعر ثابت'), ('time_materials', 'وقت ومواد'), ('milestone', 'مراحل'), ('retainer', 'اشتراك شهري')], max_length=20, verbose_name='نوع العقد')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='القيمة الإجمالية')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('payment_terms', models.TextField(blank=True, default='', verbose_name='شروط الدفع')),
                ('billing_schedule', models.CharField(choices=[('monthly', 'شهري'), ('milestone', 'بمراحل'), ('completion', 'عند الإكمال'), ('custom', 'مخصص')], default='monthly', max_length=20, verbose_name='جدول الفوترة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('suspended', 'معلق'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_contracts', to='sales.customer', verbose_name='العميل')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_contracts', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'عقد مشروع',
                'verbose_name_plural': 'عقود المشاريع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('material', 'مواد'), ('labor', 'أيدي عاملة'), ('equipment', 'معدات'), ('subcontractor', 'مقاول من الباطن'), ('travel', 'سفر'), ('overhead', 'نفقات عامة'), ('contingency', 'طوارئ'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='الفئة')),
                ('name', models.CharField(max_length=255, verbose_name='بند الميزانية')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المخطط')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ الفعلي')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'بند ميزانية',
                'verbose_name_plural': 'بنود الميزانية',
                'ordering': ['category', 'name'],
            },
        ),
    ]
