# Generated by Django 4.2.30 on 2026-05-28 10:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_timeentry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='file',
            field=models.FileField(upload_to='project_documents/', validators=[core.validators.validate_file_type], verbose_name='الملف'),
        ),
    ]
