# Generated by Django 4.2.30 on 2026-04-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_alter_salesorder_order_date'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم العقد')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان العقد')),
                ('title_en', models.CharField(blank=True, default='', max_length=200, verbose_name='عنوان العقد (إنجليزي)')),
                ('contract_type', models.CharField(choices=[('sales', 'بيع'), ('purchase', 'شراء'), ('service', 'خدمات'), ('rental', 'إيجار'), ('employment', 'توظيف'), ('consultancy', 'استشارات'), ('maintenance', 'صيانة'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='نوع العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='قيمة العقد')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('vat_inclusive', models.BooleanField(default=True, verbose_name='شامل ضريبة القيمة المضافة')),
                ('payment_terms', models.TextField(blank=True, default='', verbose_name='شروط الدفع')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('terms_conditions', models.TextField(blank=True, default='', verbose_name='الشروط والأحكام')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('expired', 'منتهي الصلاحية'), ('terminated', 'ملغي'), ('renewed', 'مجدّد'), ('cancelled', 'ملغي نهائياً')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('renewal_reminder_days', models.IntegerField(default=30, help_text='عدد الأيام قبل تاريخ الانتهاء لإرسال تذكير التجديد', verbose_name='أيام تذكير التجديد')),
                ('attachment', models.FileField(blank=True, upload_to='contracts/', verbose_name='المرفق')),
                ('signed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التوقيع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='sales.customer', verbose_name='العميل')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.project', verbose_name='المشروع')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_contracts', to=settings.AUTH_USER_MODEL, verbose_name='وقع بواسطة')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'عقد',
                'verbose_name_plural': 'العقود',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المرحلة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('overdue', 'متأخر')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإكمال')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract', verbose_name='العقد')),
            ],
            options={
                'verbose_name': 'مرحلة عقد',
                'verbose_name_plural': 'مراحل العقود',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('payment_status', models.CharField(choices=[('pending', 'معلقة'), ('paid', 'مدفوعة'), ('partially_paid', 'مدفوعة جزئياً'), ('overdue', 'متأخرة')], db_index=True, default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المدفوع')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, verbose_name='طريقة الدفع')),
                ('reference', models.CharField(blank=True, default='', max_length=100, verbose_name='المرجع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_payments', to='contracts.contract', verbose_name='العقد')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contractmilestone', verbose_name='المرحلة')),
            ],
            options={
                'verbose_name': 'دفعة عقد',
                'verbose_name_plural': 'دفعات العقود',
                'ordering': ['due_date'],
            },
        ),
    ]
