# Generated by Django 4.2.30 on 2026-04-13 12:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='رمز فريد للحساب (مثال: 1000)', max_length=20, unique=True, verbose_name='رمز الحساب')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الحساب')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الحساب (إنجليزي)')),
                ('account_type', models.CharField(choices=[('asset', 'أصول'), ('liability', 'خصوم'), ('equity', 'حقوق ملكية'), ('income', 'إيرادات'), ('expense', 'مصروفات')], db_index=True, max_length=20, verbose_name='نوع الحساب')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='الرصيد الحالي للحساب (يُحدّث تلقائياً)', max_digits=16, verbose_name='الرصيد الحالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الدليل المحاسبي',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم القيد')),
                ('entry_type', models.CharField(choices=[('manual', 'يدوي'), ('sale', 'عملية بيع'), ('payment', 'عملية دفع'), ('adjustment', 'تسوية')], db_index=True, default='manual', max_length=20, verbose_name='نوع القيد')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('reference', models.CharField(blank=True, default='', help_text='رقم مرجعي (مثال: رقم أمر البيع)', max_length=100, verbose_name='المرجع')),
                ('entry_date', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='تاريخ القيد')),
                ('is_posted', models.BooleanField(default=False, help_text='هل تم ترحيل القيد إلى الحسابات', verbose_name='مرحّل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قيد يومية',
                'verbose_name_plural': 'قيود اليومية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('debit', 'مدين'), ('credit', 'دائن')], max_length=10, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, help_text='المبلغ بالريال السعودي', max_digits=16, verbose_name='المبلغ')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='الوصف')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='accounting.account', verbose_name='الحساب')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'verbose_name': 'حركة مالية',
                'verbose_name_plural': 'الحركات المالية',
                'ordering': ['id'],
            },
        ),
    ]
