# Generated by Django 4.2.30 on 2026-04-13 16:13

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='entry_date',
            field=models.DateField(db_index=True, default=accounting.models._today, verbose_name='تاريخ القيد'),
        ),
    ]
