# Generated by Django 6.0.5 on 2026-05-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='transaction',
            name='acct_txn_entry_type_idx',
        ),
    ]
