# Generated by Django 4.2 on 2026-05-22 16:39

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0007_holidaycalendar_payslip_holiday_employmenthistory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0005_remove_transaction_acct_txn_entry_type_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(db_index=True, verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('total_allocated', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='إجمالي المبلغ الموزع')),
                ('source_balance_before', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='رصيد الحساب المصدر قبل التوزيع')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التنفيذ')),
                ('status', models.CharField(choices=[('success', 'تم بنجاح'), ('partial', 'توزيع جزئي'), ('failed', 'فشل')], db_index=True, default='success', max_length=20, verbose_name='حالة التنفيذ')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سجل توزيع',
                'verbose_name_plural': 'سجلات التوزيعات',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القاعدة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('allocation_type', models.CharField(choices=[('percentage', 'توزيع بنسبة مئوية ثابتة'), ('equal', 'توزيع متساوٍ'), ('ratio', 'توزيع بنسب مخصصة'), ('headcount', 'توزيع حسب عدد الموظفين'), ('revenue', 'توزيع حسب نسبة الإيرادات')], db_index=True, max_length=20, verbose_name='نوع التوزيع')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('is_recurring', models.BooleanField(default=False, help_text='تنفيذ القاعدة تلقائياً بشكل شهري', verbose_name='تكرار تلقائي')),
                ('recurrence_day', models.IntegerField(blank=True, help_text='يوم من الشهر لتنفيذ التوزيع التلقائي (1-28)', null=True, verbose_name='يوم التنفيذ الشهري')),
                ('effective_from', models.DateField(db_index=True, verbose_name='تاريخ السريان')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('last_executed', models.DateTimeField(blank=True, null=True, verbose_name='آخر تنفيذ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قاعدة توزيع',
                'verbose_name_plural': 'قواعد التوزيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AllocationTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='النسبة المئوية المخصصة للهدف (لنوع التوزيع بالنسبة المئوية)', max_digits=5, null=True, verbose_name='النسبة المئوية')),
                ('ratio', models.DecimalField(blank=True, decimal_places=2, help_text='النسبة المخصصة للهدف (لنوع التوزيع بالنسب المخصصة)', max_digits=10, null=True, verbose_name='النسبة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'هدف توزيع',
                'verbose_name_plural': 'أهداف التوزيع',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='رمز فريد للفرع (مثال: HQ، BR-001)', max_length=20, unique=True, verbose_name='رمز الفرع')),
                ('name', models.CharField(help_text='اسم الفرع باللغة العربية', max_length=255, verbose_name='اسم الفرع')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الفرع (إنجليزي)')),
                ('address', models.TextField(blank=True, default='', verbose_name='العنوان')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(default='السعودية', max_length=100, verbose_name='الدولة')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الهاتف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('is_headquarters', models.BooleanField(default=False, help_text='يُشير إلى أن هذا الفرع هو المقر الرئيسي للشركة', verbose_name='المقر الرئيسي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ClosureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('income_closure', 'إقفال الإيرادات'), ('expense_closure', 'إقفال المصروفات'), ('net_profit_transfer', 'تحويل صافي الربح')], db_index=True, max_length=30, verbose_name='نوع قيد الإقفال')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='الإجمالي بالريال السعودي', max_digits=16, verbose_name='إجمالي المبلغ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'قيد إقفال',
                'verbose_name_plural': 'قيود الإقفال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='رمز فريد لمركز التكلفة (مثال: CC-001)', max_length=20, unique=True, verbose_name='رمز مركز التكلفة')),
                ('name', models.CharField(max_length=255, verbose_name='اسم مركز التكلفة')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم مركز التكلفة (إنجليزي)')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='مبلغ الميزانية المخصصة لمركز التكلفة بالريال السعودي', max_digits=16, verbose_name='الميزانية المخصصة')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='إجمالي المصروفات الفعلية لمركز التكلفة', max_digits=16, verbose_name='المبلغ الفعلي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مركز تكلفة',
                'verbose_name_plural': 'مراكز التكلفة',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='رمز العملة وفق معيار ISO 4217 (مثال: SAR, USD, EUR)', max_length=3, unique=True, verbose_name='رمز العملة')),
                ('name', models.CharField(help_text='اسم العملة باللغة العربية', max_length=100, verbose_name='اسم العملة')),
                ('name_en', models.CharField(max_length=100, verbose_name='اسم العملة (إنجليزي)')),
                ('symbol', models.CharField(help_text='رمز العملة المختصر (مثال: ر.س، $، €)', max_length=5, verbose_name='رمز العملة المختصر')),
                ('is_default', models.BooleanField(default=False, help_text='العملة الأساسية للنظام (يُسمح بعملة أساسية واحدة فقط)', verbose_name='العملة الأساسية')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='سعر الصرف بالنسبة للعملة الأساسية', max_digits=12, verbose_name='سعر الصرف')),
                ('rate_date', models.DateField(auto_now=True, verbose_name='تاريخ آخر تحديث لسعر الصرف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عملة',
                'verbose_name_plural': 'العملات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='TransactionCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount', models.DecimalField(decimal_places=2, help_text='المبلغ بالعملة الأصلية', max_digits=16, verbose_name='المبلغ الأصلي')),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), help_text='سعر الصرف المُستخدم للتحويل إلى العملة الأساسية', max_digits=12, verbose_name='سعر الصرف المُستخدم')),
                ('converted_amount', models.DecimalField(decimal_places=2, help_text='المبلغ بالعملة الأساسية (ريال سعودي)', max_digits=16, verbose_name='المبلغ المحوّل')),
                ('currency', models.ForeignKey(blank=True, help_text='العملة الأصلية للحركة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency_transactions', to='accounting.currency', verbose_name='العملة')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_info', to='accounting.transaction', verbose_name='الحركة المالية')),
            ],
            options={
                'verbose_name': 'عملة الحركة',
                'verbose_name_plural': 'عملات الحركات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.ForeignKey(blank=True, help_text='الفرع المرتبط بقيد اليومية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_entries', to='accounting.branch', verbose_name='الفرع')),
                ('journal_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branch_info', to='accounting.journalentry', verbose_name='قيد اليومية')),
            ],
            options={
                'verbose_name': 'فرع القيد',
                'verbose_name_plural': 'فروع القيود',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='السنة المالية (مثال: 2024)', unique=True, verbose_name='السنة')),
                ('company_name', models.CharField(max_length=255, verbose_name='اسم الشركة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closed', 'مقفل')], db_index=True, default='open', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_years', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'سنة مالية',
                'verbose_name_plural': 'السنوات المالية',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, help_text='السنة المالية (مثال: 2024)', verbose_name='السنة')),
                ('period_type', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], db_index=True, max_length=20, verbose_name='نوع الفترة')),
                ('period_number', models.IntegerField(help_text='رقم الفترة (1-12 للشهري، 1-4 للربع سنوي، 1 للسنوي)', verbose_name='رقم الفترة')),
                ('period_start', models.DateField(db_index=True, verbose_name='بداية الفترة')),
                ('period_end', models.DateField(db_index=True, verbose_name='نهاية الفترة')),
                ('status', models.CharField(choices=[('open', 'مفتوح'), ('closing', 'قيد الإقفال'), ('closed', 'مقفل')], db_index=True, default='open', max_length=20, verbose_name='الحالة')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإقفال')),
                ('opening_balances', models.JSONField(blank=True, default=dict, help_text='أرصدة الحسابات عند بداية الفترة (JSON)', verbose_name='أرصدة الافتتاح')),
                ('closing_balances', models.JSONField(blank=True, default=dict, help_text='أرصدة الحسابات عند نهاية الفترة (JSON)', verbose_name='أرصدة الإقفال')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='أُقفل بواسطة')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='accounting.fiscalyear', verbose_name='السنة المالية')),
            ],
            options={
                'verbose_name': 'فترة محاسبية',
                'verbose_name_plural': 'الفترات المحاسبية',
                'ordering': ['year', 'period_number'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=6, help_text='سعر الصرف بالنسبة للعملة الأساسية', max_digits=12, verbose_name='سعر الصرف')),
                ('date', models.DateField(db_index=True, help_text='التاريخ الذي يُسري فيه هذا السعر', verbose_name='تاريخ السريان')),
                ('source', models.CharField(blank=True, default='', help_text='مصدر سعر الصرف (مثال: SAMA، يدوي)', max_length=50, verbose_name='مصدر السعر')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='accounting.currency', verbose_name='العملة')),
            ],
            options={
                'verbose_name': 'سجل سعر صرف',
                'verbose_name_plural': 'سجل أسعار الصرف',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['code'], name='accounting__code_00a2d6_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_610118_idx'),
        ),
        migrations.AddIndex(
            model_name='currency',
            index=models.Index(fields=['is_default'], name='accounting__is_defa_b63f33_idx'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='department',
            field=models.ForeignKey(blank=True, help_text='ربط مركز التكلفة بقسم في الموارد البشرية', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_centers', to='hr.department', verbose_name='القسم المرتبط'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cost_centers', to=settings.AUTH_USER_MODEL, verbose_name='مدير مركز التكلفة'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='الهيكل الهرمي لمراكز التكلفة', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounting.costcenter', verbose_name='مركز التكلفة الرئيسي'),
        ),
        migrations.AddField(
            model_name='closureentry',
            name='fiscal_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closure_entries', to='accounting.fiscalperiod', verbose_name='الفترة المحاسبية'),
        ),
        migrations.AddField(
            model_name='closureentry',
            name='journal_entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='closure_records', to='accounting.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AddField(
            model_name='branch',
            name='default_currency',
            field=models.ForeignKey(blank=True, help_text='العملة الافتراضية المستخدمة في هذا الفرع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='accounting.currency', verbose_name='العملة الافتراضية'),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, help_text='المستخدم المسؤول عن إدارة الفرع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL, verbose_name='مدير الفرع'),
        ),
        migrations.AddField(
            model_name='allocationtarget',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='accounting.allocationrule', verbose_name='قاعدة التوزيع'),
        ),
        migrations.AddField(
            model_name='allocationtarget',
            name='target_account',
            field=models.ForeignKey(help_text='الحساب الذي يتم التوزيع إليه', on_delete=django.db.models.deletion.PROTECT, related_name='allocation_targets', to='accounting.account', verbose_name='الحساب الهدف'),
        ),
        migrations.AddField(
            model_name='allocationtarget',
            name='target_cost_center',
            field=models.ForeignKey(help_text='مركز التكلفة الذي سيستلم الحصة', on_delete=django.db.models.deletion.PROTECT, related_name='allocation_targets', to='accounting.costcenter', verbose_name='مركز التكلفة الهدف'),
        ),
        migrations.AddField(
            model_name='allocationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AddField(
            model_name='allocationrule',
            name='source_account',
            field=models.ForeignKey(help_text='الحساب الذي يتم التوزيع منه', on_delete=django.db.models.deletion.PROTECT, related_name='allocation_rules_as_source', to='accounting.account', verbose_name='الحساب المصدر'),
        ),
        migrations.AddField(
            model_name='allocationlog',
            name='executed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نفّذ بواسطة'),
        ),
        migrations.AddField(
            model_name='allocationlog',
            name='journal_entry',
            field=models.ForeignKey(blank=True, help_text='قيد اليومية الذي تم إنشاؤه تلقائياً للتوزيع', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='allocation_logs', to='accounting.journalentry', verbose_name='قيد اليومية'),
        ),
        migrations.AddField(
            model_name='allocationlog',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='accounting.allocationrule', verbose_name='قاعدة التوزيع'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalperiod',
            unique_together={('fiscal_year', 'period_number')},
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['currency', 'date'], name='accounting__currenc_9ee645_idx'),
        ),
        migrations.AddIndex(
            model_name='exchangerate',
            index=models.Index(fields=['date'], name='accounting__date_dcceb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='exchangerate',
            unique_together={('currency', 'date')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['code'], name='accounting__code_f233aa_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_a39bf7_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['city'], name='accounting__city_a9eada_idx'),
        ),
        migrations.AddConstraint(
            model_name='allocationtarget',
            constraint=models.UniqueConstraint(fields=('rule', 'target_account'), name='unique_allocation_target_rule_account'),
        ),
    ]
