# Generated by Django 4.2.30 on 2026-04-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_alter_salesorder_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الوردية')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='وقت البدء')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت الانتهاء')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مغلقة')], default='open', max_length=20, verbose_name='الحالة')),
                ('opening_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ الافتتاحي')),
                ('closing_cash', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ النهائي')),
                ('expected_cash', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الافتتاحي + مبيعات نقدية - المردودات النقدية', max_digits=14, verbose_name='المبلغ المتوقع')),
                ('difference', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ النهائي - المبلغ المتوقع', max_digits=14, verbose_name='الفرق')),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي المبيعات')),
                ('total_transactions', models.IntegerField(default=0, verbose_name='عدد العمليات')),
                ('total_refunds', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي المردودات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('cashier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_shifts', to=settings.AUTH_USER_MODEL, verbose_name='الكاشير')),
            ],
            options={
                'verbose_name': 'وردية',
                'verbose_name_plural': 'الورديات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإيصال')),
                ('items', models.JSONField(default=list, help_text='[{product_id, name, quantity, unit_price, discount, vat, total}]', verbose_name='العناصر')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع الفرعي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الخصم')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ضريبة القيمة المضافة (15%)')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الإجمالي')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('online', 'إلكتروني'), ('mixed', 'مختلط')], default='cash', max_length=20, verbose_name='طريقة الدفع')),
                ('cash_received', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المستلم')),
                ('change_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الباقي')),
                ('card_last_four', models.CharField(blank=True, max_length=4, verbose_name='آخر 4 أرقام البطاقة')),
                ('status', models.CharField(choices=[('completed', 'مكتملة'), ('voided', 'ملغاة'), ('refunded', 'مستردة')], default='completed', max_length=20, verbose_name='الحالة')),
                ('void_reason', models.CharField(blank=True, max_length=500, verbose_name='سبب الإلغاء')),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإلغاء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_sales', to='sales.customer', verbose_name='العميل')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='pos.posshift', verbose_name='الوردية')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ألغى بواسطة')),
            ],
            options={
                'verbose_name': 'عملية بيع',
                'verbose_name_plural': 'عمليات البيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الإرجاع')),
                ('items', models.JSONField(default=list, verbose_name='العناصر المستردة')),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ الإرجاع')),
                ('refund_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('original', 'طريقة الدفع الأصلية')], default='original', max_length=20, verbose_name='طريقة الإرجاع')),
                ('reason', models.CharField(max_length=500, verbose_name='سبب الإرجاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('processed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pos.possale', verbose_name='عملية البيع')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='pos.posshift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'إرجاع',
                'verbose_name_plural': 'الإرجاعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSHoldOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hold_number', models.CharField(max_length=50, unique=True, verbose_name='رقم التعليق')),
                ('customer_name', models.CharField(blank=True, max_length=200, verbose_name='اسم العميل')),
                ('items', models.JSONField(default=list, verbose_name='العناصر')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع الفرعي')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الخصم')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='ضريبة القيمة المضافة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_recovered', models.BooleanField(default=False, verbose_name='تم الاسترجاع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='pos.posshift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'طلب معلق',
                'verbose_name_plural': 'الطلبات المعلقة',
            },
        ),
        migrations.CreateModel(
            name='CashDrawerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('opening', 'فتح'), ('closing', 'إغلاق'), ('cash_in', 'إيداع نقدي'), ('cash_out', 'سحب نقدي'), ('paid_in', 'دفع داخلي'), ('paid_out', 'دفع خارجي')], max_length=20, verbose_name='نوع الحركة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drawer_transactions', to='pos.posshift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'حركة صندوق',
                'verbose_name_plural': 'حركات الصندوق',
                'ordering': ['-created_at'],
            },
        ),
    ]
