# Generated by Django 4.2 on 2026-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_posrefund_processed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posrefund',
            name='refund_method',
            field=models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('online', 'إلكتروني'), ('mixed', 'مختلط'), ('original', 'طريقة الدفع الأصلية')], default='original', max_length=20, verbose_name='طريقة الإرجاع'),
        ),
    ]
