# Generated by Django 4.2 on 2026-05-22 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_salesorder_sales_order_status_date_idx'),
        ('pos', '0003_alter_posrefund_refund_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم القاعدة')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة'), ('fixed_amount', 'مبلغ ثابت'), ('buy_x_get_y', 'اشترِ X واحصل Y')], max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قيمة الخصم - نسبة أو مبلغ')),
                ('min_quantity', models.PositiveIntegerField(default=0, verbose_name='الحد الأدنى للكمية')),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='الحد الأقصى للخصم')),
                ('applies_to', models.CharField(choices=[('all_products', 'جميع المنتجات'), ('specific_category', 'فئة محددة'), ('specific_product', 'منتج محدد')], max_length=20, verbose_name='تنطبق على')),
                ('product_category', models.CharField(blank=True, max_length=255, verbose_name='فئة المنتجات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='الأولوية')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='صالحة من')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالحة حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قاعدة خصم',
                'verbose_name_plural': 'قواعد الخصم',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم البرنامج')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('points_per_currency', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='نقاط لكل وحدة نقدية')),
                ('min_redemption_points', models.PositiveIntegerField(default=100, verbose_name='الحد الأدنى لاستبدال النقاط')),
                ('points_value', models.DecimalField(decimal_places=2, default=0.01, max_digits=10, verbose_name='قيمة النقطة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'برنامج ولاء',
                'verbose_name_plural': 'برامج الولاء',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم قائمة الأسعار')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('is_default', models.BooleanField(default=False, verbose_name='افتراضية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='صالحة من')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='صالحة حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قائمة أسعار',
                'verbose_name_plural': 'قوائم الأسعار',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='الكود')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة'), ('fixed_amount', 'مبلغ ثابت'), ('free_shipping', 'شحن مجاني')], max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قيمة الخصم')),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الحد الأدنى للطلب')),
                ('max_uses', models.PositiveIntegerField(blank=True, null=True, verbose_name='الحد الأقصى للاستخدام')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='عدد مرات الاستخدام')),
                ('max_uses_per_customer', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى لكل عميل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='صالح من')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='صالح حتى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'كود ترويجي',
                'verbose_name_plural': 'الأكواد الترويجية',
            },
        ),
        migrations.CreateModel(
            name='RestaurantTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الطاولة')),
                ('capacity', models.PositiveIntegerField(default=4, verbose_name='السعة')),
                ('area', models.CharField(blank=True, help_text='داخلي / خارجي / تراس / خاص', max_length=50, verbose_name='المنطقة')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('occupied', 'مشغولة'), ('reserved', 'محجوزة'), ('cleaning', 'تنظيف'), ('maintenance', 'صيانة')], default='available', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('current_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pos.posshift', verbose_name='الوردية الحالية')),
            ],
            options={
                'verbose_name': 'طاولة',
                'verbose_name_plural': 'الطاولات',
            },
        ),
        migrations.CreateModel(
            name='LoyaltyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(verbose_name='النقاط')),
                ('balance_after', models.IntegerField(verbose_name='الرصيد بعد العملية')),
                ('transaction_type', models.CharField(choices=[('earned', 'مكتسبة'), ('redeemed', 'مستبدلة'), ('expired', 'منتهية الصلاحية'), ('adjusted', 'معدّلة')], max_length=20, verbose_name='نوع العملية')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_transactions', to='sales.customer', verbose_name='العميل')),
                ('loyalty_program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='pos.loyaltyprogram', verbose_name='برنامج الولاء')),
                ('pos_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loyalty_transactions', to='pos.possale', verbose_name='عملية البيع')),
            ],
            options={
                'verbose_name': 'معاملة ولاء',
                'verbose_name_plural': 'معاملات الولاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InstallmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ الإجمالي')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المدفوع')),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المتبقي')),
                ('number_of_installments', models.PositiveIntegerField(verbose_name='عدد الأقساط')),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ القسط')),
                ('paid_installments', models.PositiveIntegerField(default=0, verbose_name='الأقساط المدفوعة')),
                ('next_due_date', models.DateField(verbose_name='تاريخ الاستحقاق التالي')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('completed', 'مكتملة'), ('defaulted', 'متأخرة'), ('cancelled', 'ملغاة')], default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer', verbose_name='العميل')),
                ('pos_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='pos.possale', verbose_name='عملية البيع')),
            ],
            options={
                'verbose_name': 'خطة أقساط',
                'verbose_name_plural': 'خطط الأقساط',
            },
        ),
        migrations.CreateModel(
            name='InstallmentPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='رقم القسط')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع الفعلي')),
                ('payment_method', models.CharField(choices=[('cash', 'نقدي'), ('card', 'بطاقة'), ('online', 'إلكتروني'), ('transfer', 'تحويل')], max_length=20, verbose_name='طريقة الدفع')),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('paid', 'مدفوعة'), ('overdue', 'متأخرة'), ('partially_paid', 'مدفوعة جزئياً')], default='pending', max_length=20, verbose_name='الحالة')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المدفوع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('installment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='pos.installmentplan', verbose_name='خطة الأقساط')),
            ],
            options={
                'verbose_name': 'دفعة قسط',
                'verbose_name_plural': 'دفعات الأقساط',
                'ordering': ['installment_number'],
            },
        ),
    ]
