# Generated by Django 4.2.30 on 2026-04-18 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
        ('sales', '0003_alter_salesorder_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الشحنة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('picking', 'قيد التجهيز'), ('packed', 'مغلف'), ('in_transit', 'قيد الشحن'), ('out_for_delivery', 'خارج للتوصيل'), ('delivered', 'تم التوصيل'), ('returned', 'مرتجع'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الوزن (كجم)')),
                ('dimensions', models.TextField(blank=True, default='', verbose_name='الأبعاد')),
                ('origin_address', models.TextField(verbose_name='عنوان المصدر')),
                ('destination_address', models.TextField(verbose_name='عنوان الوجهة')),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255, verbose_name='رقم التتبع')),
                ('estimated_delivery', models.DateTimeField(blank=True, null=True, verbose_name='التوصيل المقدر')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التوصيل الفعلي')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الشحن')),
                ('insurance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ التأمين')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='sales.customer', verbose_name='العميل')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments', to='sales.salesorder', verbose_name='أمر البيع')),
            ],
            options={
                'verbose_name': 'شحنة',
                'verbose_name_plural': 'الشحنات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('carrier', models.CharField(max_length=255, verbose_name='شركة الشحن')),
                ('tracking_url', models.URLField(blank=True, verbose_name='رابط التتبع')),
                ('cost_type', models.CharField(choices=[('flat_rate', 'مبلغ ثابت'), ('weight_based', 'حسب الوزن'), ('volume_based', 'حسب الحجم'), ('free', 'مجاني')], default='flat_rate', max_length=20, verbose_name='نوع التكلفة')),
                ('base_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة الأساسية')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة لكل وحدة')),
                ('estimated_days', models.IntegerField(default=0, verbose_name='الأيام المقدرة للتوصيل')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طريقة شحن',
                'verbose_name_plural': 'طرق الشحن',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='سعر الوحدة')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الوزن (كجم)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_items', to='inventory.product', verbose_name='المنتج')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shipping.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'بند شحنة',
                'verbose_name_plural': 'بنود الشحنة',
            },
        ),
        migrations.CreateModel(
            name='ShipmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('created', 'تم الإنشاء'), ('picked', 'تم التجهيز'), ('packed', 'تم التغليف'), ('shipped', 'تم الشحن'), ('in_transit', 'قيد النقل'), ('out_for_delivery', 'خارج للتوصيل'), ('delivered', 'تم التوصيل'), ('returned', 'مرتجع'), ('exception', 'استثناء')], max_length=20, verbose_name='نوع الحدث')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='الموقع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحدث')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='shipping.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'حدث شحنة',
                'verbose_name_plural': 'أحداث الشحنة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='shipping_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='shipping.shippingmethod', verbose_name='طريقة الشحن'),
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.IntegerField(verbose_name='رقم المحاولة')),
                ('attempt_date', models.DateTimeField(verbose_name='تاريخ المحاولة')),
                ('status', models.CharField(choices=[('success', 'ناجح'), ('fail', 'فاشل'), ('partial', 'جزئي')], max_length=10, verbose_name='الحالة')),
                ('recipient_name', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم المستلم')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('signature', models.FileField(blank=True, upload_to='signatures/', verbose_name='التوقيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='shipping.shipment', verbose_name='الشحنة')),
            ],
            options={
                'verbose_name': 'محاولة توصيل',
                'verbose_name_plural': 'محاولات التوصيل',
                'ordering': ['-attempt_date'],
            },
        ),
    ]
