# Generated by Django 4.2.30 on 2026-04-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('check_in', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور')),
                ('check_out', models.TimeField(blank=True, null=True, verbose_name='وقت الانصراف')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('half_day', 'نصف يوم'), ('holiday', 'إجازة رسمية')], default='present', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-date', 'employee__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='اسم القسم')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم القسم (إنجليزي)')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم الموظف')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='اسم العائلة')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الهاتف')),
                ('gender', models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], default='', max_length=10, verbose_name='الجنس')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='المسمى الوظيفي')),
                ('hire_date', models.DateField(db_index=True, verbose_name='تاريخ التعيين')),
                ('salary', models.DecimalField(decimal_places=2, default=0, help_text='الراتب الشهري بالريال السعودي', max_digits=12, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل سكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل نقل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('on_leave', 'في إجازة'), ('suspended', 'موقوف'), ('terminated', 'منتهي الخدمة')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('bank_name', models.CharField(blank=True, default='', max_length=100, verbose_name='اسم البنك')),
                ('bank_account', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الحساب البنكي')),
                ('national_id', models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الهوية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('maternity', 'إجازة أمومة'), ('hajj', 'إجازة حج'), ('unpaid', 'إجازة بدون راتب'), ('other', 'إجازة أخرى')], db_index=True, max_length=20, verbose_name='نوع الإجازة')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('days', models.PositiveIntegerField(help_text='يُحسب تلقائياً من تاريخ البداية والنهاية', verbose_name='عدد الأيام')),
                ('reason', models.TextField(blank=True, default='', verbose_name='السبب')),
                ('approval_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('cancelled', 'ملغاة')], db_index=True, default='pending', max_length=20, verbose_name='حالة الموافقة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'طلب إجازة',
                'verbose_name_plural': 'طلبات الإجازات',
                'ordering': ['-created_at'],
            },
        ),
    ]
