# Generated by Django 4.2.30 on 2026-04-28 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الوردية')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Shift Name (EN)')),
                ('start_time', models.TimeField(verbose_name='وقت البداية')),
                ('end_time', models.TimeField(verbose_name='وقت النهاية')),
                ('break_duration', models.PositiveIntegerField(default=60, help_text='بالدقائق', verbose_name='مدة الاستراحة (دقيقة)')),
                ('is_night', models.BooleanField(default=False, verbose_name='وردية ليلية')),
                ('applicable_days', models.JSONField(default=list, help_text='قائمة بأرقام الأيام: 0=أحد, 1=إثنين, ... 6=سبت', verbose_name='أيام التطبيق')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'وردية',
                'verbose_name_plural': 'الورديات',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='hr.department', verbose_name='القسم الأب'),
        ),
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_date', models.DateField(verbose_name='تاريخ السريان')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='hr.employee', verbose_name='الموظف')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='hr.shift', verbose_name='الوردية')),
            ],
            options={
                'verbose_name': 'تعيين وردية',
                'verbose_name_plural': 'تعيينات الورديات',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_period', models.CharField(choices=[('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], max_length=20, verbose_name='فترة التقييم')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('quarter', models.IntegerField(blank=True, help_text='1-4 للتقييم الربعي', null=True, verbose_name='الربع')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('goals_rating', models.IntegerField(blank=True, null=True, verbose_name='تقييم الأهداف')),
                ('competencies_rating', models.IntegerField(blank=True, null=True, verbose_name='تقييم الكفاءات')),
                ('teamwork_rating', models.IntegerField(blank=True, null=True, verbose_name='العمل الجماعي')),
                ('communication_rating', models.IntegerField(blank=True, null=True, verbose_name='التواصل')),
                ('initiative_rating', models.IntegerField(blank=True, null=True, verbose_name='المبادرة')),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='التقييم العام')),
                ('strengths', models.TextField(blank=True, default='', verbose_name='نقاط القوة')),
                ('areas_for_improvement', models.TextField(blank=True, default='', verbose_name='مجالات التحسين')),
                ('goals_for_next_period', models.TextField(blank=True, default='', verbose_name='أهداف الفترة القادمة')),
                ('comments', models.TextField(blank=True, default='', verbose_name='ملاحظات عامة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('self_review', 'تقييم ذاتي'), ('manager_review', 'تقييم المدير'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاكتمال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_reviews', to='hr.employee', verbose_name='الموظف')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews_conducted', to=settings.AUTH_USER_MODEL, verbose_name='المقيّم')),
            ],
            options={
                'verbose_name': 'تقييم أداء',
                'verbose_name_plural': 'تقييمات الأداء',
                'ordering': ['-year', '-created_at'],
                'unique_together': {('employee', 'review_period', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('maternity', 'إجازة أمومة'), ('hajj', 'إجازة حج'), ('unpaid', 'إجازة بدون راتب'), ('other', 'إجازة أخرى')], max_length=20, verbose_name='نوع الإجازة')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('total_days', models.PositiveIntegerField(default=30, verbose_name='الرصيد الإجمالي')),
                ('used_days', models.PositiveIntegerField(default=0, verbose_name='الأيام المستخدمة')),
                ('remaining_days', models.PositiveIntegerField(default=30, verbose_name='الأيام المتبقية')),
                ('carried_over', models.PositiveIntegerField(default=0, verbose_name='الأيام المنقولة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'رصيد الإجازات',
                'verbose_name_plural': 'أرصدة الإجازات',
                'ordering': ['employee__first_name', 'leave_type', '-year'],
                'unique_together': {('employee', 'leave_type', 'year')},
            },
        ),
    ]
