# Generated by Django 6.0.4 on 2026-05-01 20:04

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_shift_department_parent_employeeshift_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='performancereview',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, null=True, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='communication_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='التواصل'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='competencies_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الكفاءات'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='goals_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='تقييم الأهداف'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='initiative_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='المبادرة'),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='teamwork_rating',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='العمل الجماعي'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_attendance_employee_date'),
        ),
        migrations.AddConstraint(
            model_name='leavebalance',
            constraint=models.UniqueConstraint(fields=('employee', 'leave_type', 'year'), name='unique_leave_balance_employee_type_year'),
        ),
        migrations.AddConstraint(
            model_name='performancereview',
            constraint=models.UniqueConstraint(fields=('employee', 'review_period', 'year', 'quarter'), name='unique_performance_review_employee_period_year_quarter'),
        ),
    ]
