# Generated by Django 6.0.5 on 2026-05-06 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attendance',
            name='hr_attendance_emp_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='hr_emp_dept_status_idx',
        ),
    ]
