# Generated by Django 4.2 on 2026-05-22 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0006_remove_attendance_hr_attendance_emp_date_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم التقويم')),
                ('year', models.IntegerField(db_index=True, verbose_name='السنة')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'تقويم إجازات',
                'verbose_name_plural': 'تقويمات الإجازات',
                'ordering': ['-year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='الشهر')),
                ('year', models.IntegerField(db_index=True, verbose_name='السنة')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل سكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل نقل')),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='أجر إضافي')),
                ('bonuses', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مكافآت')),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصومات أخرى')),
                ('insurance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم التأمينات')),
                ('tax_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم الضرائب')),
                ('loan_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم القروض')),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصم السلف')),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='خصومات أخرى')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('paid', 'مدفوع')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('payment_method', models.CharField(blank=True, choices=[('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدي'), ('check', 'شيك')], default='', max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التوليد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payslips_approved', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'قسيمة راتب',
                'verbose_name_plural': 'قسائم الرواتب',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الإجازة')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='اسم الإجازة (إنجليزي)')),
                ('date', models.DateField(db_index=True, verbose_name='التاريخ')),
                ('holiday_type', models.CharField(choices=[('public', 'إجازة رسمية'), ('company', 'إجازة الشركة'), ('optional', 'إجازة اختيارية')], default='public', max_length=20, verbose_name='نوع الإجازة')),
                ('is_recurring', models.BooleanField(default=False, help_text='إجازات مثل عيد الفطر وعيد الأضحى تتكرر سنوياً', verbose_name='إجازة سنوية متكررة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='hr.holidaycalendar', verbose_name='التقويم')),
            ],
            options={
                'verbose_name': 'إجازة رسمية',
                'verbose_name_plural': 'الإجازات الرسمية',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='EmploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('hire', 'تعيين'), ('transfer', 'نقل'), ('promotion', 'ترقية'), ('demotion', 'تنزيل'), ('salary_change', 'تغيير راتب'), ('title_change', 'تغيير مسمى وظيفي'), ('termination', 'إنهاء خدمة'), ('rehire', 'إعادة تعيين')], db_index=True, max_length=20, verbose_name='نوع الإجراء')),
                ('position', models.CharField(blank=True, default='', max_length=255, verbose_name='المسمى الوظيفي')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الراتب')),
                ('effective_date', models.DateField(db_index=True, verbose_name='تاريخ السريان')),
                ('previous_department', models.CharField(blank=True, default='', max_length=255, verbose_name='القسم السابق')),
                ('previous_position', models.CharField(blank=True, default='', max_length=255, verbose_name='المسمى الوظيفي السابق')),
                ('previous_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='الراتب السابق')),
                ('reason', models.TextField(blank=True, default='', verbose_name='السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_histories_created', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employment_histories', to='hr.department', verbose_name='القسم')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_history', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل وظيفي',
                'verbose_name_plural': 'السجلات الوظيفية',
                'ordering': ['-effective_date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(fields=('employee', 'month', 'year'), name='unique_payslip_employee_month_year'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('calendar', 'date'), name='unique_holiday_calendar_date'),
        ),
    ]
