# Generated by Django 4.2.30 on 2026-05-28 10:49

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_course_documenttemplate_healthinsurance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(upload_to='document_templates/', validators=[core.validators.validate_file_type], verbose_name='ملف القالب'),
        ),
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to='employee_documents/', validators=[core.validators.validate_file_type], verbose_name='الملف'),
        ),
    ]
