# Generated by Django 4.2.30 on 2026-04-13 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_backup_enabled', models.BooleanField(default=False, verbose_name='النسخ التلقائي مفعّل')),
                ('backup_frequency', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=20, verbose_name='تكرار النسخ')),
                ('backup_time', models.CharField(default='02:00', help_text='وقت تنفيذ النسخ الاحتياطي (HH:MM)', max_length=10, verbose_name='وقت النسخ')),
                ('keep_backups_count', models.IntegerField(default=30, help_text='الحد الأقصى لعدد النسخ الاحتياطية المحفوظة', verbose_name='عدد النسخ المحفوظة')),
                ('backup_directory', models.CharField(default='backups', max_length=500, verbose_name='مجلد النسخ الاحتياطية')),
                ('include_media', models.BooleanField(default=False, verbose_name='تضمين ملفات الوسائط')),
            ],
            options={
                'verbose_name': 'إعداد النسخ الاحتياطي',
                'verbose_name_plural': 'إعدادات النسخ الاحتياطي',
            },
        ),
        migrations.CreateModel(
            name='CronJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المهمة')),
                ('task', models.CharField(choices=[('auto_backup_daily', 'نسخ احتياطي يومي'), ('auto_backup_weekly', 'نسخ احتياطي أسبوعي'), ('auto_backup_monthly', 'نسخ احتياطي شهري'), ('inventory_alerts', 'تنبيهات المخزون المنخفض'), ('recurring_invoices', 'فواتير متكررة'), ('clean_old_logs', 'تنظيف السجلات القديمة'), ('clean_old_backups', 'تنظيف النسخ الاحتياطية القديمة'), ('employee_attendance_reminder', 'تذكير الحضور'), ('expense_alerts', 'تنبيهات المصروفات'), ('project_deadline_alerts', 'تنبيهات مواعيد المشاريع')], max_length=50, verbose_name='نوع المهمة')),
                ('frequency', models.CharField(choices=[('every_minute', 'كل دقيقة'), ('every_5_minutes', 'كل 5 دقائق'), ('every_15_minutes', 'كل 15 دقيقة'), ('every_30_minutes', 'كل 30 دقيقة'), ('hourly', 'كل ساعة'), ('every_6_hours', 'كل 6 ساعات'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=20, verbose_name='التكرار')),
                ('cron_expression', models.CharField(blank=True, help_text='مثال: 0 2 * * * (يوميا الساعة 2 صباحا)', max_length=100, verbose_name='تعبير كرون')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('paused', 'متوقف'), ('running', 'جاري التنفيذ'), ('failed', 'فاشل')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('last_run', models.DateTimeField(blank=True, null=True, verbose_name='آخر تنفيذ')),
                ('next_run', models.DateTimeField(blank=True, null=True, verbose_name='التنفيذ التالي')),
                ('last_run_status', models.CharField(blank=True, max_length=20, verbose_name='حالة آخر تنفيذ')),
                ('last_run_duration', models.FloatField(blank=True, null=True, verbose_name='مدة آخر تنفيذ (ثانية)')),
                ('run_count', models.IntegerField(default=0, verbose_name='عدد مرات التنفيذ')),
                ('fail_count', models.IntegerField(default=0, verbose_name='عدد مرات الفشل')),
                ('config', models.JSONField(blank=True, default=dict, help_text='إعدادات خاصة بالمهمة مثل عتبة المخزون أو البريد الإلكتروني', verbose_name='إعدادات إضافية')),
                ('error_message', models.TextField(blank=True, verbose_name='رسالة الخطأ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cron_jobs', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة مجدولة',
                'verbose_name_plural': 'المهام المجدولة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_path', models.CharField(max_length=500, verbose_name='مسار الملف')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='حجم الملف (بايت)')),
                ('backup_type', models.CharField(choices=[('manual', 'يدوي'), ('auto_daily', 'يومي تلقائي'), ('auto_weekly', 'أسبوعي تلقائي'), ('auto_monthly', 'شهري تلقائي')], default='manual', max_length=20, verbose_name='نوع النسخة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('completed', 'مكتمل'), ('failed', 'فاشل'), ('restoring', 'جاري الاستعادة')], default='completed', max_length=20, verbose_name='الحالة')),
                ('tables_count', models.IntegerField(default=0, verbose_name='عدد الجداول')),
                ('records_count', models.IntegerField(default=0, verbose_name='عدد السجلات')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backups', to=settings.AUTH_USER_MODEL, verbose_name='تم الإنشاء بواسطة')),
            ],
            options={
                'verbose_name': 'نسخة احتياطية',
                'verbose_name_plural': 'النسخ الاحتياطية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('debug', 'تصحيح'), ('info', 'معلومة'), ('warning', 'تحذير'), ('error', 'خطأ'), ('critical', 'حرج')], db_index=True, default='error', max_length=20, verbose_name='المستوى')),
                ('source', models.CharField(choices=[('backend', 'الباكلاند'), ('frontend', 'الفرانت اند'), ('api', 'واجهة API'), ('cron', 'مهام مجدولة'), ('backup', 'النسخ الاحتياطي'), ('database', 'قاعدة البيانات'), ('auth', 'المصادقة'), ('other', 'أخرى')], db_index=True, default='backend', max_length=20, verbose_name='المصدر')),
                ('code', models.CharField(blank=True, db_index=True, max_length=100, verbose_name='رمز الخطأ')),
                ('message', models.TextField(verbose_name='رسالة الخطأ')),
                ('stack_trace', models.TextField(blank=True, verbose_name='تتبع المكدس')),
                ('url_path', models.CharField(blank=True, max_length=500, verbose_name='المسار')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='طريقة الطلب')),
                ('request_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات الطلب')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('is_resolved', models.BooleanField(db_index=True, default=False, verbose_name='تم الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='ملاحظات الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='تاريخ التسجيل')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_errors', to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='error_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'خطأ',
                'verbose_name_plural': 'سجل الأخطاء',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['level', 'source', 'created_at'], name='maintenance_level_a419d9_idx'), models.Index(fields=['is_resolved', 'created_at'], name='maintenance_is_reso_a5d65e_idx')],
            },
        ),
    ]
