# Generated by Django 4.2.30 on 2026-04-18 17:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        ('hr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('tender_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم المناقصة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('tender_type', models.CharField(choices=[('open', 'مفتوحة'), ('restricted', 'مقيدة'), ('invitation', 'بدعوة')], default='open', max_length=20, verbose_name='نوع المناقصة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('published', 'منشورة'), ('evaluation', 'قيد التقييم'), ('awarded', 'مترسية'), ('cancelled', 'ملغاة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النشر')),
                ('closing_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإغلاق')),
                ('opening_date', models.DateField(blank=True, null=True, verbose_name='تاريخ فتح العروض')),
                ('estimated_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='القيمة التقديرية')),
                ('terms_conditions', models.TextField(blank=True, default='', verbose_name='الشروط والأحكام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='hr.department', verbose_name='القسم')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenders', to='projects.project', verbose_name='المشروع')),
            ],
            options={
                'verbose_name': 'مناقصة',
                'verbose_name_plural': 'المناقصات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم العرض')),
                ('submission_date', models.DateField(verbose_name='تاريخ التقديم')),
                ('status', models.CharField(choices=[('submitted', 'مقدم'), ('qualified', 'مؤهل'), ('disqualified', 'غير مؤهل'), ('selected', 'مختار'), ('rejected', 'مرفوض')], db_index=True, default='submitted', max_length=20, verbose_name='الحالة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='إجمالي المبلغ')),
                ('validity_days', models.IntegerField(default=90, verbose_name='أيام الصلاحية')),
                ('technical_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة الفنية')),
                ('financial_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة المالية')),
                ('total_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='الدرجة الإجمالية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_bids', to='purchases.supplier', verbose_name='المورد')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='tenders.tender', verbose_name='المناقصة')),
            ],
            options={
                'verbose_name': 'عرض مناقصة',
                'verbose_name_plural': 'عروض المناقصات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion', models.CharField(max_length=255, verbose_name='معيار التقييم')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الوزن')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الدرجة')),
                ('weighted_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='الدرجة الموزونة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tenders.tenderbid', verbose_name='العرض')),
                ('evaluator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='المقيّم')),
            ],
            options={
                'verbose_name': 'تقييم مناقصة',
                'verbose_name_plural': 'تقييمات المناقصات',
                'ordering': ['criterion'],
            },
        ),
        migrations.CreateModel(
            name='TenderDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المستند')),
                ('file', models.FileField(upload_to='tenders/', verbose_name='الملف')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tenders.tender', verbose_name='المناقصة')),
            ],
            options={
                'verbose_name': 'مستند مناقصة',
                'verbose_name_plural': 'مستندات المناقصات',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TenderAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_date', models.DateField(verbose_name='تاريخ الترسية')),
                ('contract_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='قيمة العقد')),
                ('contract_duration_days', models.IntegerField(default=0, verbose_name='مدة العقد (بالأيام)')),
                ('terms', models.TextField(blank=True, default='', verbose_name='شروط العقد')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tender_awards_approved', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='tenders.tenderbid', verbose_name='العرض الفائز')),
                ('tender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='tenders.tender', verbose_name='المناقصة')),
            ],
            options={
                'verbose_name': 'ترسية مناقصة',
                'verbose_name_plural': 'ترسيات المناقصات',
                'ordering': ['-created_at'],
            },
        ),
    ]
