# Generated by Django 4.2.30 on 2026-05-05 18:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0003_alter_purchaserequisition_requested_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0003_alter_salesorder_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplierScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0, help_text='0-100')),
                ('delivery_score', models.FloatField(default=0, help_text='On-time delivery rate 0-100')),
                ('quality_score', models.FloatField(default=0, help_text='Technical quality score 0-100')),
                ('financial_score', models.FloatField(default=0, help_text='Financial score 0-100')),
                ('fill_rate', models.FloatField(default=0, help_text='Order fill rate 0-100')),
                ('total_orders', models.IntegerField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('rating_tier', models.CharField(choices=[('excellent', 'ممتاز'), ('good', 'جيد'), ('average', 'متوسط'), ('poor', 'ضعيف')], default='average', max_length=20)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_score', to='purchases.supplier')),
            ],
            options={
                'ordering': ['-overall_score'],
            },
        ),
        migrations.CreateModel(
            name='ModelMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(db_index=True, max_length=50)),
                ('model_version', models.CharField(default='v1', max_length=20)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('training_duration_ms', models.IntegerField(default=0, help_text='Training time in milliseconds')),
                ('mape', models.FloatField(blank=True, help_text='Mean Absolute Percentage Error', null=True)),
                ('mae', models.FloatField(blank=True, help_text='Mean Absolute Error', null=True)),
                ('rmse', models.FloatField(blank=True, help_text='Root Mean Squared Error', null=True)),
                ('r2_score', models.FloatField(blank=True, help_text='R-squared', null=True)),
                ('extra_metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['model_type', 'is_active'], name='analytics_m_model_t_652d40_idx')],
            },
        ),
        migrations.CreateModel(
            name='ForecastResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_type', models.CharField(choices=[('sales', 'تنبؤ المبيعات'), ('demand', 'تنبؤ الطلب'), ('cashflow', 'تنبؤ التدفق النقدي'), ('expense', 'تنبؤ المصروفات')], db_index=True, max_length=20)),
                ('period_type', models.CharField(choices=[('daily', 'يومي'), ('weekly', 'أسبوعي'), ('monthly', 'شهري')], default='daily', max_length=10)),
                ('forecast_date', models.DateField(db_index=True)),
                ('predicted_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('lower_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('upper_bound', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('accuracy_score', models.FloatField(blank=True, null=True)),
                ('entity_id', models.IntegerField(blank=True, help_text='e.g. product_id for demand forecast', null=True)),
                ('entity_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['forecast_date'],
                'indexes': [models.Index(fields=['model_type', 'forecast_date'], name='analytics_f_model_t_a6732d_idx'), models.Index(fields=['model_type', 'entity_id'], name='analytics_f_model_t_040757_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_name', models.CharField(choices=[('VIP', 'عميل مميز'), ('Loyal', 'عميل وفّي'), ('Regular', 'عميل عادي'), ('At Risk', 'عميل مهدد'), ('Lost', 'عميل فاقد')], db_index=True, max_length=20)),
                ('r_score', models.IntegerField(help_text='Recency score (1-5)')),
                ('f_score', models.IntegerField(help_text='Frequency score (1-5)')),
                ('m_score', models.IntegerField(help_text='Monetary score (1-5)')),
                ('rfm_total', models.IntegerField(help_text='Total RFM score (3-15)')),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('order_count', models.IntegerField(default=0)),
                ('avg_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('last_order_date', models.DateField(blank=True, null=True)),
                ('first_order_date', models.DateField(blank=True, null=True)),
                ('customer_tenure_days', models.IntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='segment', to='sales.customer')),
            ],
            options={
                'ordering': ['-rfm_total'],
                'indexes': [models.Index(fields=['segment_name'], name='analytics_c_segment_e15587_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anomaly_type', models.CharField(choices=[('expense', 'مصروفات شاذة'), ('sales', 'مبيعات شاذة'), ('payment', 'مدفوعات شاذة'), ('inventory', 'مخزون شاذ')], db_index=True, max_length=20)),
                ('detected_at', models.DateTimeField(db_index=True)),
                ('entity_type', models.CharField(help_text='e.g. transaction, order, invoice', max_length=50)),
                ('entity_id', models.IntegerField(blank=True, null=True)),
                ('expected_range_min', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('expected_range_max', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('actual_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('anomaly_score', models.FloatField(help_text='0.0 = normal, 1.0 = extreme anomaly')),
                ('severity', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('critical', 'حرج')], db_index=True, default='medium', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('is_reviewed', models.BooleanField(db_index=True, default=False)),
                ('review_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
                'indexes': [models.Index(fields=['anomaly_type', 'severity', 'is_reviewed'], name='analytics_a_anomaly_a89d93_idx'), models.Index(fields=['-detected_at'], name='analytics_a_detecte_819815_idx')],
            },
        ),
    ]
