# Generated by Django 4.2.30 on 2026-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyrecord',
            name='anomaly_type',
            field=models.CharField(choices=[('expense', 'مصروفات شاذة'), ('sales', 'مبيعات شاذة'), ('payment', 'مدفوعات شاذة'), ('purchase', 'مشتريات شاذة'), ('payroll', 'رواتب شاذة')], db_index=True, max_length=20),
        ),
    ]
