# Generated by Django 4.2.30 on 2026-04-18 11:02

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('sales', '0003_alter_salesorder_order_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الفاتورة')),
                ('invoice_type', models.CharField(choices=[('sales', 'فاتورة مبيعات'), ('purchase', 'فاتورة مشتريات'), ('credit_note', 'إشعار دائن'), ('debit_note', 'إشعار مدين')], max_length=20, verbose_name='نوع الفاتورة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المجموع الفرعي')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قيمة الخصم')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مبلغ الخصم')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='مبلغ الضريبة')),
                ('total_after_discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي بعد الخصم')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='الإجمالي النهائي')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('payment_status', models.CharField(choices=[('unpaid', 'غير مدفوعة'), ('partially_paid', 'مدفوعة جزئياً'), ('paid', 'مدفوعة'), ('overdue', 'متأخرة'), ('cancelled', 'ملغاة')], default='unpaid', max_length=20, verbose_name='حالة الدفع')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='المبلغ المدفوع')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسلة'), ('accepted', 'مقبولة'), ('partially_paid', 'مدفوعة جزئياً'), ('paid', 'مدفوعة'), ('cancelled', 'ملغاة')], default='draft', max_length=20, verbose_name='الحالة')),
                ('tax_number', models.CharField(blank=True, max_length=30, verbose_name='الرقم الضريبي (العميل/المورد)')),
                ('company_tax_number', models.CharField(default='300000000000003', max_length=30, verbose_name='الرقم الضريبي للشركة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('terms_conditions', models.TextField(blank=True, verbose_name='الشروط والأحكام')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.customer', verbose_name='العميل')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesorder', verbose_name='أمر البيع')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchases.supplier', verbose_name='المورد')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('first', 'تذكير أول'), ('second', 'تذكير ثاني'), ('final', 'تذكير نهائي'), ('legal', 'إجراء قانوني')], max_length=20, verbose_name='نوع التذكير')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('sent_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('sent_via', models.CharField(choices=[('email', 'بريد إلكتروني'), ('sms', 'رسالة نصية'), ('whatsapp', 'واتساب'), ('manual', 'يدوي')], max_length=20, verbose_name='طريقة الإرسال')),
                ('status', models.CharField(choices=[('sent', 'تم الإرسال'), ('pending', 'قيد الانتظار'), ('failed', 'فشل')], default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoicing.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'تذكير دفع',
                'verbose_name_plural': 'تذكيرات الدفع',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الدفعة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدي'), ('cheque', 'شيك'), ('card', 'بطاقة'), ('online', 'دفع إلكتروني')], max_length=20, verbose_name='طريقة الدفع')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='رقم المرجع')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='اسم البنك')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='invoicing.invoice', verbose_name='الفاتورة')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'المدفوعات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('unit', models.CharField(default='piece', max_length=20, verbose_name='الوحدة')),
                ('discount_type', models.CharField(choices=[('percentage', 'نسبة مئوية'), ('fixed', 'مبلغ ثابت')], default='percentage', max_length=20, verbose_name='نوع الخصم')),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, verbose_name='قيمة الخصم')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('15.00'), max_digits=5, verbose_name='نسبة الضريبة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المجموع الفرعي')),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ الضريبة')),
                ('total', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الإجمالي')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice', verbose_name='الفاتورة')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'بند فاتورة',
                'verbose_name_plural': 'بنود الفاتورة',
            },
        ),
    ]
