# Generated by Django 4.2.30 on 2026-04-18 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('campaign_type', models.CharField(choices=[('email', 'بريد إلكتروني'), ('sms', 'رسائل نصية'), ('social_media', 'وسائل التواصل الاجتماعي'), ('ads', 'إعلانات'), ('event', 'فعالية')], max_length=20, verbose_name='نوع الحملة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('paused', 'متوقفة'), ('completed', 'مكتملة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الميزانية')),
                ('actual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='التكلفة الفعلية')),
                ('target_audience', models.CharField(blank=True, default='', max_length=500, verbose_name='الجمهور المستهدف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
            ],
            options={
                'verbose_name': 'حملة تسويقية',
                'verbose_name_plural': 'الحملات التسويقية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=100, verbose_name='الاسم الأخير')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف')),
                ('mobile', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف المحمول')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='الشركة')),
                ('position', models.CharField(blank=True, default='', max_length=200, verbose_name='المنصب')),
                ('source', models.CharField(blank=True, choices=[('website', 'الموقع الإلكتروني'), ('referral', 'إحالة'), ('social_media', 'وسائل التواصل الاجتماعي'), ('phone', 'الهاتف'), ('email', 'البريد الإلكتروني'), ('event', 'فعالية'), ('other', 'أخرى')], default='', max_length=20, verbose_name='المصدر')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('inactive', 'غير نشط'), ('lost', 'مفقود')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
            ],
            options={
                'verbose_name': 'جهة اتصال',
                'verbose_name_plural': 'جهات الاتصال',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('criteria', models.JSONField(blank=True, null=True, verbose_name='معايير التجزئة')),
                ('customer_count', models.IntegerField(default=0, verbose_name='عدد العملاء')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='الحد الأقصى 100%', max_digits=5, verbose_name='نسبة الخصم')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'شريحة عملاء',
                'verbose_name_plural': 'شرائح العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='القيمة')),
                ('probability', models.IntegerField(default=0, help_text='نسبة احتمالية إغلاق الفرصة (0-100)', verbose_name='نسبة الاحتمالية')),
                ('expected_close_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإغلاق المتوقع')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('contacted', 'تم التواصل'), ('qualified', 'مؤهل'), ('proposal', 'عرض سعر'), ('negotiation', 'تفاوض'), ('won', 'مكتسب'), ('lost', 'مفقود')], db_index=True, default='new', max_length=20, verbose_name='الحالة')),
                ('pipeline_stage', models.CharField(choices=[('lead', 'فرصة'), ('qualified', 'مؤهل'), ('proposal', 'عرض سعر'), ('negotiation', 'تفاوض'), ('closed_won', 'مكتمل - مكتسب'), ('closed_lost', 'مكتمل - مفقود')], db_index=True, default='lead', max_length=20, verbose_name='مرحلة خط المبيعات')),
                ('source', models.CharField(blank=True, choices=[('website', 'الموقع الإلكتروني'), ('referral', 'إحالة'), ('social_media', 'وسائل التواصل الاجتماعي'), ('phone', 'الهاتف'), ('email', 'البريد الإلكتروني'), ('event', 'فعالية'), ('other', 'أخرى')], default='', max_length=20, verbose_name='المصدر')),
                ('lost_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='سبب الفقدان')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='crm.contact', verbose_name='جهة الاتصال')),
            ],
            options={
                'verbose_name': 'فرصة بيع',
                'verbose_name_plural': 'فرص البيع',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('call', 'مكالمة'), ('email', 'بريد إلكتروني'), ('meeting', 'اجتماع'), ('task', 'مهمة'), ('note', 'ملاحظة')], max_length=20, verbose_name='نوع النشاط')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='التاريخ المجدول')),
                ('completed', models.BooleanField(default=False, verbose_name='مكتمل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أكتمل بواسطة')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead', verbose_name='فرصة البيع')),
            ],
            options={
                'verbose_name': 'نشاط فرصة',
                'verbose_name_plural': 'أنشطة الفرص',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('email_sent', 'بريد مرسل'), ('call_made', 'مكالمة تمت'), ('meeting_scheduled', 'اجتماع مجدول'), ('form_submitted', 'نموذج مُرسل'), ('purchase_made', 'عملية شراء')], max_length=20, verbose_name='نوع النشاط')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('activity_date', models.DateTimeField(verbose_name='تاريخ النشاط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.campaign', verbose_name='الحملة التسويقية')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact', verbose_name='جهة الاتصال')),
            ],
            options={
                'verbose_name': 'نشاط حملة',
                'verbose_name_plural': 'أنشطة الحملات',
                'ordering': ['-activity_date'],
            },
        ),
    ]
