# Generated by Django 4.2 on 2026-05-22 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.CharField(blank=True, default='', help_text='اسم الشركة النصي (للتوافق العكسي)', max_length=200, verbose_name='الشركة'),
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم الشركة')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='الاسم بالإنجليزية')),
                ('industry', models.CharField(blank=True, default='', max_length=200, verbose_name='القطاع الصناعي')),
                ('website', models.URLField(blank=True, default='', verbose_name='الموقع الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='الهاتف')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('address', models.CharField(blank=True, default='', max_length=500, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='المدينة')),
                ('country', models.CharField(blank=True, default='', max_length=100, verbose_name='البلد')),
                ('company_type', models.CharField(choices=[('customer', 'عميل'), ('partner', 'شريك'), ('vendor', 'مورد'), ('competitor', 'منافس'), ('other', 'أخرى')], db_index=True, default='customer', max_length=20, verbose_name='نوع الشركة')),
                ('annual_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='الإيرادات السنوية')),
                ('employee_count', models.IntegerField(default=0, verbose_name='عدد الموظفين')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='company_account',
            field=models.ForeignKey(blank=True, help_text='الربط بنموذج الشركة الرسمي', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='crm.company', verbose_name='الشركة (الحساب)'),
        ),
    ]
