# Generated by Django 4.2 on 2026-05-22 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_alter_contact_company_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_number', models.CharField(help_text='توليد تلقائي: QT-YYYYMMDD-XXXX', max_length=50, unique=True, verbose_name='رقم العرض')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('sent', 'مرسل'), ('accepted', 'مقبول'), ('rejected', 'مرفوض'), ('expired', 'منتهي الصلاحية'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('valid_until', models.DateField(verbose_name='صالح حتى')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المجموع الفرعي')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الخصم')),
                ('vat_percent', models.DecimalField(decimal_places=2, default=15, max_digits=5, verbose_name='نسبة ضريبة القيمة المضافة')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ ضريبة القيمة المضافة')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('terms_conditions', models.TextField(blank=True, default='', verbose_name='الشروط والأحكام')),
                ('converted_to_order', models.BooleanField(default=False, verbose_name='تم التحويل لأمر بيع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.company', verbose_name='الشركة')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.contact', verbose_name='جهة الاتصال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='crm.lead', verbose_name='فرصة البيع')),
            ],
            options={
                'verbose_name': 'عرض سعر',
                'verbose_name_plural': 'عروض الأسعار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SLAPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم السياسة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], db_index=True, max_length=20, verbose_name='الأولوية')),
                ('first_response_time', models.PositiveIntegerField(help_text='بالدقائق', verbose_name='وقت الاستجابة الأولية')),
                ('resolution_time', models.PositiveIntegerField(help_text='بالدقائق', verbose_name='وقت الحل')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'سياسة SLA',
                'verbose_name_plural': 'سياسات SLA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(help_text='توليد تلقائي: TK-YYYYMMDD-XXXX', max_length=50, unique=True, verbose_name='رقم التذكرة')),
                ('subject', models.CharField(max_length=500, verbose_name='الموضوع')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('new', 'جديد'), ('in_progress', 'قيد التنفيذ'), ('pending_customer', 'بانتظار العميل'), ('resolved', 'تم الحل'), ('closed', 'مغلق'), ('reopened', 'مُعاد فتحه')], db_index=True, default='new', max_length=30, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], db_index=True, default='medium', max_length=20, verbose_name='الأولوية')),
                ('category', models.CharField(choices=[('technical', 'تقني'), ('billing', 'فواتير'), ('general', 'عام'), ('complaint', 'شكوى'), ('feature_request', 'طلب ميزة'), ('other', 'أخرى')], db_index=True, default='general', max_length=30, verbose_name='التصنيف')),
                ('resolution', models.TextField(blank=True, default='', verbose_name='الحل')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('first_response_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاستجابة الأولى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_tickets', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.company', verbose_name='الشركة')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.contact', verbose_name='جهة الاتصال')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('sla_policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='crm.slapolicy', verbose_name='سياسة SLA')),
            ],
            options={
                'verbose_name': 'تذكرة دعم',
                'verbose_name_plural': 'تذاكر الدعم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('is_internal', models.BooleanField(default=False, verbose_name='داخلي - لا يراه العميل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أُنشئ بواسطة')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='crm.ticket', verbose_name='التذكرة')),
            ],
            options={
                'verbose_name': 'تعليق تذكرة',
                'verbose_name_plural': 'تعليقات التذاكر',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('product', 'منتج'), ('service', 'خدمة'), ('custom', 'مخصص')], max_length=20, verbose_name='نوع البند')),
                ('item_name', models.CharField(max_length=500, verbose_name='اسم البند')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='سعر الوحدة')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='نسبة الخصم')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='الكمية × سعر الوحدة × (1 - نسبة الخصم / 100)', max_digits=14, verbose_name='المجموع الفرعي')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='الترتيب')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='crm.quotation', verbose_name='عرض السعر')),
            ],
            options={
                'verbose_name': 'بند عرض سعر',
                'verbose_name_plural': 'بنود عروض الأسعار',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_type', models.CharField(choices=[('order', 'أمر بيع'), ('project', 'مشروع'), ('contract', 'عقد')], db_index=True, max_length=20, verbose_name='نوع البيع')),
                ('reference_id', models.PositiveIntegerField(help_text='رقم التعريف - order/project/contract id', verbose_name='معرف المرجع')),
                ('reference_number', models.CharField(blank=True, default='', help_text='رقم المرجع - SO-xxx, إلخ', max_length=100, verbose_name='رقم المرجع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='قيمة المبيعات')),
                ('commission_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='نسبة العمولة')),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ العمولة')),
                ('status', models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('paid', 'مدفوع'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('period_month', models.PositiveIntegerField(help_text='1-12', verbose_name='الشهر')),
                ('period_year', models.PositiveIntegerField(verbose_name='السنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('salesperson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL, verbose_name='مندوب المبيعات')),
            ],
            options={
                'verbose_name': 'عمولة',
                'verbose_name_plural': 'العمولات',
                'ordering': ['-created_at'],
            },
        ),
    ]
