# Generated by Django 6.0.4 on 2026-04-18 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finding_number', models.CharField(max_length=50, verbose_name='رقم الملاحظة')),
                ('title', models.CharField(max_length=255, verbose_name='العنوان')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('severity', models.CharField(choices=[('info', 'معلومات'), ('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], db_index=True, default='medium', max_length=20, verbose_name='الخطورة')),
                ('category', models.CharField(choices=[('financial', 'مالي'), ('operational', 'تشغيلي'), ('compliance', 'توافق'), ('control', 'رقابي'), ('risk', 'مخاطر'), ('fraud', 'احتيال'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='التصنيف')),
                ('condition', models.TextField(help_text='الوضع الحالي الذي تم رصده', verbose_name='الشرط')),
                ('criteria', models.TextField(blank=True, default='', help_text='المعيار أو المعايير التي يجب الالتزام بها', verbose_name='المعيار')),
                ('cause', models.TextField(blank=True, default='', help_text='السبب الجذري للملاحظة', verbose_name='السبب')),
                ('effect', models.TextField(blank=True, default='', help_text='الأثر المحتمل للملاحظة', verbose_name='الأثر')),
                ('recommendation', models.TextField(help_text='التوصيات لمعالجة الملاحظة', verbose_name='التوصية')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('in_progress', 'قيد المعالجة'), ('resolved', 'تم الحل'), ('closed', 'مغلقة'), ('accepted', 'مقبولة')], db_index=True, default='open', max_length=20, verbose_name='الحالة')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الاستحقاق')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الحل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings_resolved', to=settings.AUTH_USER_MODEL, verbose_name='تم الحل بواسطة')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_findings_responsible', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'ملاحظة تدقيق',
                'verbose_name_plural': 'ملاحظات التدقيق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('document', 'مستند'), ('interview_observation', 'مقابلة/ملاحظة'), ('data_analysis', 'تحليل بيانات'), ('physical', 'فحص مادي'), ('other', 'أخرى')], max_length=30, verbose_name='نوع الدليل')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('file', models.FileField(blank=True, upload_to='audit_evidence/', verbose_name='الملف')),
                ('collected_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الجمع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('collected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_evidence_collected', to=settings.AUTH_USER_MODEL, verbose_name='تم الجمع بواسطة')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='internalaudit.auditfinding', verbose_name='ملاحظة التدقيق')),
            ],
            options={
                'verbose_name': 'دليل تدقيق',
                'verbose_name_plural': 'أدلة التدقيق',
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='اسم خطة التدقيق', max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('fiscal_year', models.IntegerField(verbose_name='السنة المالية')),
                ('audit_type', models.CharField(choices=[('financial', 'تدقيق مالي'), ('operational', 'تدقيق تشغيلي'), ('compliance', 'تدقيق توافق'), ('it', 'تدقيق تقنية المعلومات'), ('investigation', 'تحقيق'), ('special', 'تدقيق خاص')], db_index=True, max_length=20, verbose_name='نوع التدقيق')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('team_members', models.TextField(blank=True, default='', help_text='أسماء أعضاء فريق التدقيق', verbose_name='أعضاء الفريق')),
                ('scope', models.TextField(blank=True, default='', verbose_name='نطاق التدقيق')),
                ('objectives', models.TextField(blank=True, default='', verbose_name='أهداف التدقيق')),
                ('risk_level', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], db_index=True, default='medium', max_length=20, verbose_name='مستوى المخاطر')),
                ('budget_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='ساعات الميزانية')),
                ('actual_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='الساعات الفعلية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_plans_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_plans', to='hr.department', verbose_name='القسم')),
                ('lead_auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_audit_plans', to=settings.AUTH_USER_MODEL, verbose_name='رئيس فريق التدقيق')),
            ],
            options={
                'verbose_name': 'خطة تدقيق',
                'verbose_name_plural': 'خطط التدقيق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='audit_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='internalaudit.auditplan', verbose_name='خطة التدقيق'),
        ),
        migrations.CreateModel(
            name='ComplianceCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('regulation', models.CharField(max_length=255, verbose_name='اللائحة/النظام')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('frequency', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], max_length=20, verbose_name='التكرار')),
                ('last_check', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر فحص')),
                ('next_check', models.DateField(verbose_name='تاريخ الفحص القادم')),
                ('status', models.CharField(choices=[('compliant', 'متوافق'), ('partially_compliant', 'متوافق جزئياً'), ('non_compliant', 'غير متوافق'), ('not_checked', 'لم يتم الفحص')], db_index=True, default='not_checked', max_length=20, verbose_name='الحالة')),
                ('findings', models.TextField(blank=True, default='', verbose_name='الملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks', to='hr.department', verbose_name='القسم')),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compliance_checks_responsible', to=settings.AUTH_USER_MODEL, verbose_name='المسؤول')),
            ],
            options={
                'verbose_name': 'فحص توافق',
                'verbose_name_plural': 'فحوصات التوافق',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_number', models.CharField(max_length=50, verbose_name='رقم الإجراء')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('critical', 'حرج')], db_index=True, default='medium', max_length=20, verbose_name='الأولوية')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('overdue', 'متأخر'), ('cancelled', 'ملغي')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('evidence_of_completion', models.TextField(blank=True, default='', verbose_name='دليل الإنجاز')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحقق')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_assigned', to=settings.AUTH_USER_MODEL, verbose_name='مسند إلى')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions_verified', to=settings.AUTH_USER_MODEL, verbose_name='تم التحقق بواسطة')),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='internalaudit.auditfinding', verbose_name='ملاحظة التدقيق')),
            ],
            options={
                'verbose_name': 'إجراء تصحيحي',
                'verbose_name_plural': 'الإجراءات التصحيحية',
                'ordering': ['-created_at'],
                'unique_together': {('finding', 'action_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='auditfinding',
            unique_together={('audit_plan', 'finding_number')},
        ),
    ]
