# Generated by Django 4.2.30 on 2026-04-18 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('version', models.IntegerField(default=1, verbose_name='الإصدار')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشطة'), ('archived', 'مؤرشفة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('effective_date', models.DateField(blank=True, null=True, verbose_name='تاريخ السريان')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'قائمة مواد',
                'verbose_name_plural': 'قوائم المواد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='الموقع')),
                ('capacity', models.IntegerField(default=1, verbose_name='السعة')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('maintenance', 'صيانة'), ('inactive', 'غير نشط')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('cost_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الساعة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'مركز عمل',
                'verbose_name_plural': 'مراكز العمل',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='رقم الخطوة')),
                ('operation_name', models.CharField(max_length=255, verbose_name='اسم العملية')),
                ('estimated_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الوقت المقدر (دقائق)')),
                ('cost_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الوحدة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='manufacturing.billofmaterials', verbose_name='قائمة المواد')),
                ('work_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routing_steps', to='manufacturing.workcenter', verbose_name='مركز العمل')),
            ],
            options={
                'verbose_name': 'خطوة مسار إنتاج',
                'verbose_name_plural': 'خطوات مسارات الإنتاج',
                'ordering': ['bom', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الكمية المطلوبة')),
                ('quantity_produced', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الكمية المنتجة')),
                ('quantity_defective', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الكمية المعيبة')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('planned', 'مخطط'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغى')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('planned_start_date', models.DateField(verbose_name='تاريخ البدء المخطط')),
                ('planned_end_date', models.DateField(verbose_name='تاريخ الانتهاء المخطط')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ البدء الفعلي')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء الفعلي')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'عالي'), ('urgent', 'عاجل')], db_index=True, default='medium', max_length=20, verbose_name='الأولوية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='manufacturing.billofmaterials', verbose_name='قائمة المواد')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_orders', to='inventory.product', verbose_name='المنتج')),
            ],
            options={
                'verbose_name': 'أمر إنتاج',
                'verbose_name_plural': 'أوامر الإنتاج',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('setup', 'إعداد'), ('production', 'إنتاج'), ('quality_check', 'فحص الجودة'), ('packaging', 'تغليف'), ('maintenance', 'صيانة')], max_length=20, verbose_name='نوع العملية')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الكمية')),
                ('defect_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='كمية المعيوبات')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('log_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ السجل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المشغل')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='manufacturing.productionorder', verbose_name='أمر الإنتاج')),
            ],
            options={
                'verbose_name': 'سجل إنتاج',
                'verbose_name_plural': 'سجلات الإنتاج',
                'ordering': ['-log_date'],
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الكمية')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='تكلفة الوحدة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='manufacturing.billofmaterials', verbose_name='قائمة المواد')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_items', to='inventory.product', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'بند قائمة مواد',
                'verbose_name_plural': 'بنود قوائم المواد',
                'ordering': ['bom', 'id'],
            },
        ),
    ]
