# Generated by Django 4.2 on 2026-05-22 14:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import startup_finance.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0005_remove_salesorder_sales_order_status_date_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StartupProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم الشركة')),
                ('industry', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='القطاع')),
                ('stage', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('growth', 'Growth'), ('profitable', 'مربحة')], db_index=True, default='seed', max_length=30, verbose_name='مرحلة التمويل')),
                ('founded_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التأسيس')),
                ('team_size', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='حجم الفريق')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('initial_funding', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي التمويل المرفوع حتى الآن', max_digits=16, verbose_name='التمويل الأولي')),
                ('monthly_recurring_revenue', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي الاشتراكات الشهرية النشطة', max_digits=16, verbose_name='الإيرادات المتكررة الشهرية (MRR)')),
                ('monthly_operating_expenses', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي المصروفات الشهرية (رواتب + تشغيل)', max_digits=16, verbose_name='المصروفات التشغيلية الشهرية')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, help_text='السيولة المتاحة حالياً', max_digits=16, verbose_name='الرصيد النقدي الحالي')),
            ],
            options={
                'verbose_name': 'ملف الشركة الناشئة',
                'verbose_name_plural': 'ملفات الشركات الناشئة',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='اسم الخطة')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('price_monthly', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر الشهري')),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='يُعرض خصم عند اختيار الفوترة السنوية', max_digits=12, null=True, verbose_name='السعر السنوي')),
                ('features', models.JSONField(blank=True, default=dict, help_text='قائمة الميزات كـ JSON array', verbose_name='الميزات')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشطة')),
                ('trial_days', models.PositiveIntegerField(default=0, verbose_name='فترة التجربة (أيام)')),
                ('max_users', models.PositiveIntegerField(default=1, verbose_name='الحد الأقصى للمستخدمين')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', help_text='يُملأ تلقائياً من العميل أو يدوياً', max_length=255, verbose_name='اسم العميل')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('trialing', 'فترة تجربة'), ('past_due', 'متأخر الدفع'), ('paused', 'موقوف مؤقتاً'), ('cancelled', 'ملغي'), ('churned', 'فقد العميل')], db_index=True, default='active', max_length=15, verbose_name='الحالة')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('yearly', 'سنوي')], db_index=True, default='monthly', max_length=15, verbose_name='دورة الفوترة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ الاشتراك')),
                ('start_date', models.DateField(db_index=True, verbose_name='تاريخ البدء')),
                ('end_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='نهاية فترة التجربة')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=500, verbose_name='سبب الإلغاء')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='sales.customer', verbose_name='العميل')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='startup_finance.subscriptionplan', verbose_name='الخطة')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='startup_finance.startupprofile', verbose_name='الشركة الناشئة')),
            ],
            options={
                'verbose_name': 'دورة اشتراك',
                'verbose_name_plural': 'دورات الاشتراك',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FundingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('pre_seed', 'Pre-Seed'), ('seed', 'Seed'), ('angel', 'Angel'), ('series_a', 'Series A'), ('series_b', 'Series B'), ('series_c', 'Series C'), ('bridge', 'Bridge Loan'), ('convertible', 'Convertable Note'), ('grant', 'منحة'), ('revenue', 'تمويل ذاتي من الإيرادات')], db_index=True, max_length=20, verbose_name='نوع الجولة')),
                ('round_name', models.CharField(blank=True, default='', max_length=100, verbose_name='اسم الجولة')),
                ('amount_raised', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ المرفوع')),
                ('valuation_pre_money', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='التقييم قبل الجولة')),
                ('valuation_post_money', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='التقييم بعد الجولة')),
                ('investor_names', models.TextField(blank=True, default='', help_text='قائمة مفصولة بفواصل', verbose_name='أسماء المستثمرين')),
                ('equity_diluted', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='نسبة التخفيف %')),
                ('round_date', models.DateField(db_index=True, default=startup_finance.models._today, verbose_name='تاريخ الجولة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_rounds', to='startup_finance.startupprofile', verbose_name='الشركة الناشئة')),
            ],
            options={
                'verbose_name': 'جولة تمويل',
                'verbose_name_plural': 'جولات التمويل',
                'ordering': ['-round_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, verbose_name='الشهر')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='إجمالي الإيرادات')),
                ('mrr', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='الإيرادات المتكررة الشهرية (MRR)')),
                ('arr', models.DecimalField(decimal_places=2, default=0, help_text='MRR × 12', max_digits=18, verbose_name='الإيرادات السنوية المتكررة (ARR)')),
                ('arpu', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='متوسط الإيراد لكل مستخدم (ARPU)')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='إجمالي المصروفات')),
                ('burn_rate', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='معدل الحرق (Burn Rate)')),
                ('cac', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='متوسط تكلفة الاكتساب (CAC)')),
                ('ltv', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='متوسط قيمة العميل (LTV)')),
                ('runway_months', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='أشهر المشاركة المتبقية (Runway)')),
                ('gross_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش الربح الإجمالي %')),
                ('net_margin_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='هامش صافي الربح %')),
                ('ltv_cac_ratio', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='نسبة LTV/CAC')),
                ('quick_ratio', models.DecimalField(decimal_places=2, default=0, help_text='(New MRR + Expansion) / (Churn + Contraction)', max_digits=6, verbose_name='Quick Ratio (MRR Expansion)')),
                ('total_subscribers', models.PositiveIntegerField(default=0, verbose_name='إجمالي المشتركين')),
                ('new_subscribers', models.PositiveIntegerField(default=0, verbose_name='المشتركين الجدد')),
                ('churned_subscribers', models.PositiveIntegerField(default=0, verbose_name='العملاء المفقودين')),
                ('churn_rate_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='معدل فقد العملاء %')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='الرصيد النقدي')),
                ('total_funding_raised', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='إجمالي التمويل المرفوع')),
                ('calculated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ الحساب')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpis', to='startup_finance.startupprofile', verbose_name='الشركة الناشئة')),
            ],
            options={
                'verbose_name': 'مؤشر أداء مالي',
                'verbose_name_plural': 'مؤشرات الأداء المالي',
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='FinancialEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('revenue', 'إيراد'), ('expense', 'مصروف'), ('investment', 'استثمار'), ('refund', 'استرداد'), ('adjustment', 'تسوية')], db_index=True, max_length=15, verbose_name='نوع القيد')),
                ('category', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='الفئة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, verbose_name='المبلغ')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='الوصف')),
                ('entry_date', models.DateField(db_index=True, default=startup_finance.models._today, verbose_name='تاريخ القيد')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='يُمرر من التكاملات الخارجية لمنع التكرار', max_length=255, unique=True, verbose_name='مفتاح عدم التكرار')),
                ('external_reference', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='المرجع الخارجي')),
                ('external_source', models.CharField(blank=True, default='', help_text='مثال: stripe, paypal, manual', max_length=50, verbose_name='المصدر الخارجي')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_entries', to='startup_finance.startupprofile', verbose_name='الشركة الناشئة')),
            ],
            options={
                'verbose_name': 'قيد مالي',
                'verbose_name_plural': 'القيود المالية',
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, db_index=True, default='', max_length=255, verbose_name='اسم العميل')),
                ('acquisition_channel', models.CharField(blank=True, db_index=True, default='', help_text='مثال: Google Ads, SEO, Referral, Direct', max_length=50, verbose_name='قناة الاكتساب')),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, help_text='إجمالي ما أُنفق على تسويق وبيع هذا العميل', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='تكلفة الاكتساب (CAC)')),
                ('monthly_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الإيراد الشهري من العميل')),
                ('months_active', models.PositiveIntegerField(default=1, help_text='كم شهراً ظل العميل مشتركاً', verbose_name='عدد أشهر النشاط')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='إجمالي الإيراد من العميل')),
                ('projected_ltv', models.DecimalField(blank=True, decimal_places=2, help_text='يُحسب تلقائياً: monthly_revenue × avg_lifetime_months × margin', max_digits=16, null=True, verbose_name='قيمة العميل المتوقعة (LTV)')),
                ('cohort', models.DateField(blank=True, db_index=True, help_text='شهر اكتساب العميل', null=True, verbose_name='المجموعة (Cohort)')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='metrics', to='sales.customer', verbose_name='العميل')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_metrics', to='startup_finance.startupprofile', verbose_name='الشركة الناشئة')),
            ],
            options={
                'verbose_name': 'مقاييس العميل',
                'verbose_name_plural': 'مقاييس العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BurnRateEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(db_index=True, help_text='أول يوم في الشهر', verbose_name='الشهر')),
                ('category', models.CharField(choices=[('payroll', 'الرواتب والأجور'), ('rent', 'الإيجار'), ('marketing', 'التسويق والإعلان'), ('software', 'البرمجيات والاشتراكات'), ('infrastructure', 'البنية التحتية والاستضافة'), ('operations', 'العمليات والتشغيل'), ('legal', 'الشؤون القانونية'), ('travel', 'السفر والتنقل'), ('misc', 'متنوع')], db_index=True, max_length=20, verbose_name='الفئة')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16, validators=[django.core.validators.MinValueValidator(0)], verbose_name='المبلغ')),
                ('entry_type', models.CharField(choices=[('expense', 'مصروف'), ('revenue', 'إيراد')], db_index=True, default='expense', max_length=10, verbose_name='النوع')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='الوصف')),
                ('is_recurring', models.BooleanField(db_index=True, default=False, help_text='هل هذا المصروف يتكرر شهرياً؟', verbose_name='مصروف متكرر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أدخل بواسطة')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='burn_rate_entries', to='startup_finance.startupprofile', verbose_name='الشركة الناشئة')),
            ],
            options={
                'verbose_name': 'سجل معدل الحرق',
                'verbose_name_plural': 'سجلات معدل الحرق',
                'ordering': ['-month', 'category'],
            },
        ),
        migrations.AddIndex(
            model_name='subscriptioncycle',
            index=models.Index(fields=['startup', 'status'], name='startup_fin_startup_c7bc4c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycle',
            index=models.Index(fields=['status', 'start_date'], name='startup_fin_status_db8949_idx'),
        ),
        migrations.AddIndex(
            model_name='subscriptioncycle',
            index=models.Index(fields=['plan', 'status'], name='startup_fin_plan_id_8769c4_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinground',
            index=models.Index(fields=['startup', 'round_type'], name='startup_fin_startup_4f96d3_idx'),
        ),
        migrations.AddIndex(
            model_name='fundinground',
            index=models.Index(fields=['round_date'], name='startup_fin_round_d_6d8613_idx'),
        ),
        migrations.AddIndex(
            model_name='financialkpi',
            index=models.Index(fields=['startup', '-month'], name='startup_fin_startup_2e3668_idx'),
        ),
        migrations.AddIndex(
            model_name='financialkpi',
            index=models.Index(fields=['month'], name='startup_fin_month_c4b031_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='financialkpi',
            unique_together={('startup', 'month')},
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['startup', 'entry_type', 'entry_date'], name='startup_fin_startup_04e823_idx'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['entry_date'], name='startup_fin_entry_d_8b226c_idx'),
        ),
        migrations.AddIndex(
            model_name='financialentry',
            index=models.Index(fields=['external_source', 'external_reference'], name='startup_fin_externa_3023f2_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetric',
            index=models.Index(fields=['startup', 'acquisition_channel'], name='startup_fin_startup_665c79_idx'),
        ),
        migrations.AddIndex(
            model_name='customermetric',
            index=models.Index(fields=['cohort'], name='startup_fin_cohort_f662b5_idx'),
        ),
        migrations.AddIndex(
            model_name='burnrateentry',
            index=models.Index(fields=['startup', 'month', 'entry_type'], name='startup_fin_startup_37f789_idx'),
        ),
        migrations.AddIndex(
            model_name='burnrateentry',
            index=models.Index(fields=['month', 'category'], name='startup_fin_month_b88ef3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='burnrateentry',
            unique_together={('startup', 'month', 'category', 'entry_type')},
        ),
    ]
