# Generated by Django 4.2.30 on 2026-04-13 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المنتج')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('sku', models.CharField(db_index=True, help_text='رمز فريد لتحديد المنتج', max_length=100, unique=True, verbose_name='رمز المنتج (SKU)')),
                ('quantity', models.PositiveIntegerField(default=0, help_text='الكمية الحالية في المخزون', verbose_name='الكمية المتوفرة')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='سعر البيع لكل وحدة', max_digits=12, verbose_name='سعر الوحدة')),
                ('reorder_level', models.PositiveIntegerField(default=10, help_text='الحد الأدنى للكمية قبل طلب المزيد', verbose_name='حد إعادة الطلب')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='الحذف الناعم - يعطل المنتج بدلاً من حذفه', verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='inventory_p_sku_f85905_idx'), models.Index(fields=['is_active'], name='inventory_p_is_acti_47a270_idx'), models.Index(fields=['name'], name='inventory_p_name_f6a6a1_idx')],
            },
        ),
    ]
