# Generated by Django 4.2.30 on 2026-04-13 12:39
# Rewritten: removed inventory dependency, merged 0001+0002, replaced product FK with product_name

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='اسم العميل')),
                ('email', models.EmailField(blank=True, db_index=True, default='', max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, default='', max_length=30, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, default='', verbose_name='العنوان')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم الأمر')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('confirmed', 'مؤكد'), ('shipped', 'تم الشحن'), ('delivered', 'تم التسليم'), ('cancelled', 'ملغي')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('order_date', models.DateField(db_index=True, default=sales.models._today, verbose_name='تاريخ الأمر')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الإجمالي')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sales.customer', verbose_name='العميل')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'أمر بيع',
                'verbose_name_plural': 'أوامر البيع',
                'ordering': ['-created_at'],
                'permissions': [('confirm_order', 'Can confirm sales orders'), ('cancel_order', 'Can cancel sales orders'), ('change_status', 'Can change order status')],
            },
        ),
        migrations.CreateModel(
            name='SalesOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, verbose_name='اسم المنتج')),
                ('quantity', models.PositiveIntegerField(verbose_name='الكمية')),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='السعر عند إنشاء الأمر', max_digits=12, verbose_name='سعر الوحدة')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الإجمالي الفرعي')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.salesorder', verbose_name='أمر البيع')),
            ],
            options={
                'verbose_name': 'بند أمر بيع',
                'verbose_name_plural': 'بنود أوامر البيع',
                'unique_together': {('order', 'product_name')},
            },
        ),
    ]
