# Generated by Django 4.2.30 on 2026-04-18 11:02

from django.db import migrations, models
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorder',
            name='order_date',
            field=models.DateField(db_index=True, default=sales.models._today, verbose_name='تاريخ الأمر'),
        ),
    ]
