# Generated by Django 4.2.30 on 2026-04-18 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PensionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pension_scheme', models.CharField(max_length=255, verbose_name='نظام المعاش')),
                ('contribution_type', models.CharField(choices=[('employer', 'صاحب العمل'), ('employee', 'الموظف'), ('both', 'الطرفان')], default='both', max_length=20, verbose_name='نوع المساهمة')),
                ('monthly_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المساهمة الشهرية')),
                ('employer_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مساهمة صاحب العمل')),
                ('employee_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مساهمة الموظف')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('suspended', 'معلق'), ('withdrawn', 'مسحوب'), ('retired', 'متقاعد')], db_index=True, default='active', max_length=20, verbose_name='الحالة')),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي المساهمات')),
                ('last_contribution_date', models.DateField(blank=True, null=True, verbose_name='تاريخ آخر مساهمة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_records', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سجل معاش',
                'verbose_name_plural': 'سجلات المعاشات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PensionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('payment_date', models.DateField(verbose_name='تاريخ الدفع')),
                ('month', models.IntegerField(verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدي')], default='bank_transfer', max_length=20, verbose_name='طريقة الدفع')),
                ('reference_number', models.CharField(blank=True, default='', max_length=100, verbose_name='رقم المرجع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوعة'), ('failed', 'فاشلة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('pension_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='insurance.pensionrecord', verbose_name='سجل المعاش')),
            ],
            options={
                'verbose_name': 'دفعة معاش',
                'verbose_name_plural': 'دفعات المعاشات',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_number', models.CharField(max_length=100, unique=True, verbose_name='رقم البوليصة')),
                ('policy_name', models.CharField(max_length=255, verbose_name='اسم البوليصة')),
                ('insurance_provider', models.CharField(max_length=255, verbose_name='شركة التأمين')),
                ('insurance_type', models.CharField(choices=[('health', 'تأمين صحي'), ('life', 'تأمين حياة'), ('property', 'تأمين ممتلكات'), ('vehicle', 'تأمين مركبات'), ('liability', 'تأمين مسؤولية'), ('workers_comp', 'تأمين إصابات عمل'), ('other', 'أخرى')], max_length=20, verbose_name='نوع التأمين')),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ التغطية')),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ القسط')),
                ('premium_frequency', models.CharField(choices=[('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('annual', 'سنوي')], default='annual', max_length=15, verbose_name='تكرار القسط')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('expired', 'منتهية'), ('cancelled', 'ملغاة'), ('pending', 'قيد الانتظار')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('insured_entity', models.CharField(choices=[('company', 'الشركة'), ('employee', 'موظف'), ('asset', 'أصل'), ('vehicle', 'مركبة')], max_length=20, verbose_name='الجهة المؤمنة')),
                ('related_entity_id', models.IntegerField(blank=True, null=True, verbose_name='معرف الكيان المرتبط')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'بوليصة تأمين',
                'verbose_name_plural': 'بوالص التأمين',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=100, unique=True, verbose_name='رقم الطلب')),
                ('claim_type', models.CharField(choices=[('full', 'تعويض كامل'), ('partial', 'تعويض جزئي')], default='full', max_length=10, verbose_name='نوع التعويض')),
                ('incident_date', models.DateField(verbose_name='تاريخ الحادث')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('claimed_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المطلوب')),
                ('approved_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المعتمد')),
                ('status', models.CharField(choices=[('submitted', 'مقدم'), ('under_review', 'قيد المراجعة'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('paid', 'مدفوع')], db_index=True, default='submitted', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('documents', models.TextField(blank=True, default='', verbose_name='المستندات')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='insurance.insurancepolicy', verbose_name='البوليصة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='راجع بواسطة')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insurance_claims_submitted', to=settings.AUTH_USER_MODEL, verbose_name='قدم بواسطة')),
            ],
            options={
                'verbose_name': 'طلب تعويض',
                'verbose_name_plural': 'طلبات التعويض',
                'ordering': ['-created_at'],
            },
        ),
    ]
