# Generated by Django 4.2.30 on 2026-04-13 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'إنشاء'), ('update', 'تعديل'), ('delete', 'حذف'), ('soft_delete', 'حذف ناعم'), ('restore', 'إعادة تفعيل'), ('status_change', 'تغيير حالة'), ('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('export', 'تصدير'), ('import', 'استيراد'), ('backup', 'نسخ احتياطي'), ('other', 'أخرى')], db_index=True, max_length=20, verbose_name='الإجراء')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='اسم النموذج')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='رقم الكائن')),
                ('object_repr', models.CharField(blank=True, max_length=255, verbose_name='تمثيل الكائن')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='التغييرات')),
                ('old_values', models.JSONField(blank=True, default=dict, verbose_name='القيم القديمة')),
                ('new_values', models.JSONField(blank=True, default=dict, verbose_name='القيم الجديدة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='متصفح المستخدم')),
                ('url_path', models.CharField(blank=True, max_length=500, verbose_name='المسار')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='التاريخ')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل تدقيق',
                'verbose_name_plural': 'سجلات التدقيق',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model_name', 'action', 'created_at'], name='auditlog_au_model_n_5f0cb3_idx'), models.Index(fields=['user', 'created_at'], name='auditlog_au_user_id_4cf170_idx')],
            },
        ),
    ]
