# Generated by Django 4.2.30 on 2026-04-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchases', '0001_initial'),
        ('sales', '0003_alter_salesorder_order_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(db_index=True, max_length=200, verbose_name='اسم الحساب')),
                ('account_type', models.CharField(choices=[('bank_account', 'حساب بنكي'), ('cash_box', 'صندوق نقدي'), ('mobile_wallet', 'محفظة موبايل')], db_index=True, max_length=20, verbose_name='نوع الحساب')),
                ('bank_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم البنك')),
                ('account_number', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, default='', max_length=50, verbose_name='الآيبان')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الرصيد الحالي')),
                ('is_default', models.BooleanField(db_index=True, default=False, verbose_name='افتراضي')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'حساب مالي',
                'verbose_name_plural': 'الحسابات المالية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم التسوية')),
                ('period_start', models.DateField(verbose_name='بداية الفترة')),
                ('period_end', models.DateField(verbose_name='نهاية الفترة')),
                ('system_balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='رصيد النظام')),
                ('actual_balance', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الرصيد الفعلي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('reconciled', 'متوازن'), ('discrepancy', 'فارق')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='payments.paymentaccount', verbose_name='الحساب')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='بواسطة')),
            ],
            options={
                'verbose_name': 'تسوية',
                'verbose_name_plural': 'التسويات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True, verbose_name='رقم العملية')),
                ('transaction_type', models.CharField(choices=[('receipt', 'إيصال قبض'), ('payment', 'دفع'), ('transfer', 'تحويل'), ('adjustment', 'تسوية يدوية')], db_index=True, max_length=20, verbose_name='نوع العملية')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('currency', models.CharField(default='SAR', max_length=3, verbose_name='العملة')),
                ('reference_type', models.CharField(blank=True, choices=[('invoice', 'فاتورة'), ('salary', 'راتب'), ('loan', 'قرض'), ('purchase', 'مشتريات'), ('sale', 'مبيعات'), ('other', 'أخرى')], default='', max_length=50, verbose_name='نوع المرجع')),
                ('reference_id', models.IntegerField(blank=True, null=True, verbose_name='رقم المرجع')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('transaction_date', models.DateField(db_index=True, verbose_name='تاريخ العملية')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدي'), ('cheque', 'شيك'), ('card', 'بطاقة'), ('mobile', 'موبايل')], max_length=20, verbose_name='طريقة الدفع')),
                ('cheque_number', models.CharField(blank=True, default='', max_length=50, verbose_name='رقم الشيك')),
                ('status', models.CharField(choices=[('completed', 'مكتمل'), ('pending', 'قيد الانتظار'), ('cancelled', 'ملغي')], db_index=True, default='completed', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='payments.paymentaccount', verbose_name='الحساب')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='sales.customer', verbose_name='العميل')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='purchases.supplier', verbose_name='المورد')),
                ('to_account', models.ForeignKey(blank=True, help_text='يُستخدم عند التحويل بين الحسابات', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='payments.paymentaccount', verbose_name='حساب المستلم')),
            ],
            options={
                'verbose_name': 'عملية مالية',
                'verbose_name_plural': 'العمليات المالية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cheque_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='رقم الشيك')),
                ('bank_name', models.CharField(max_length=200, verbose_name='اسم البنك')),
                ('branch_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم الفرع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('due_date', models.DateField(db_index=True, verbose_name='تاريخ الاستحقاق')),
                ('payer_name', models.CharField(max_length=200, verbose_name='اسم المحرر')),
                ('payee_name', models.CharField(max_length=200, verbose_name='اسم المستفيد')),
                ('cheque_type', models.CharField(choices=[('incoming', 'شيك وارد'), ('outgoing', 'شيك صادر')], db_index=True, max_length=20, verbose_name='نوع الشيك')),
                ('status', models.CharField(choices=[('received', 'مستلم'), ('deposited', 'مودع'), ('cleared', 'مصروف'), ('bounced', 'مرتجع'), ('cancelled', 'ملغي')], db_index=True, default='received', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='sales.customer', verbose_name='العميل')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='purchases.supplier', verbose_name='المورد')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheques', to='payments.financialtransaction', verbose_name='العملية المالية')),
            ],
            options={
                'verbose_name': 'شيك',
                'verbose_name_plural': 'الشيكات',
                'ordering': ['-created_at'],
            },
        ),
    ]
