# Generated by Django 4.2.30 on 2026-04-13 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='اسم التصنيف')),
                ('name_en', models.CharField(blank=True, default='', max_length=255, verbose_name='التصنيف (إنجليزي)')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'تصنيف مستندات',
                'verbose_name_plural': 'تصنيفات المستندات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='عنوان المستند')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('module', models.CharField(choices=[('general', 'عام'), ('inventory', 'المخازن'), ('sales', 'المبيعات'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('purchases', 'المشتريات'), ('projects', 'المشاريع')], db_index=True, default='general', max_length=20, verbose_name='الوحدة')),
                ('object_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('file', models.FileField(upload_to='documents/%Y/%m/', verbose_name='الملف')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف')),
                ('file_type', models.CharField(blank=True, max_length=100, verbose_name='نوع الملف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.documentcategory', verbose_name='التصنيف')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='documents_d_content_ba3031_idx')],
            },
        ),
    ]
