# Generated by Django 4.2.30 on 2026-04-18 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: يناير 2025', max_length=100, verbose_name='الاسم')),
                ('month', models.IntegerField(help_text='رقم الشهر (1-12)', verbose_name='الشهر')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('processing', 'قيد المعالجة'), ('paid', 'مدفوع'), ('closed', 'مغلق')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('total_employees', models.IntegerField(default=0, verbose_name='إجمالي الموظفين')),
                ('total_salaries', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الرواتب')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الخصومات')),
                ('total_net', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='صافي الإجمالي')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'فترة الرواتب',
                'verbose_name_plural': 'فترات الرواتب',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='SalaryAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('purpose', models.CharField(max_length=200, verbose_name='الغرض')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة'), ('paid', 'مدفوعة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('monthly_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='الخصم الشهري')),
                ('months_remaining', models.IntegerField(default=0, verbose_name='الأشهر المتبقية')),
                ('advance_date', models.DateField(verbose_name='تاريخ السلفة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advances', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'سلفة',
                'verbose_name_plural': 'السلف',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EndOfServiceBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_of_service', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='سنوات الخدمة')),
                ('total_service_days', models.IntegerField(verbose_name='إجمالي أيام الخدمة')),
                ('last_salary', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='آخر راتب')),
                ('total_benefit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='إجمالي المكافأة')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الخصم')),
                ('net_benefit', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='صافي المكافأة')),
                ('calculation_date', models.DateField(verbose_name='تاريخ الحساب')),
                ('status', models.CharField(choices=[('calculated', 'محسوبة'), ('paid', 'مدفوعة'), ('partial', 'مدفوعة جزئياً')], db_index=True, default='calculated', max_length=20, verbose_name='الحالة')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_of_service', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'مكافأة نهاية خدمة',
                'verbose_name_plural': 'مكافآت نهاية الخدمة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='مبلغ القرض')),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='القسط الشهري')),
                ('months', models.IntegerField(verbose_name='عدد الأشهر')),
                ('months_remaining', models.IntegerField(verbose_name='الأشهر المتبقية')),
                ('purpose', models.CharField(max_length=200, verbose_name='الغرض')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('active', 'نشط'), ('completed', 'مكتمل'), ('defaulted', 'متعثر')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='hr.employee', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'قرض',
                'verbose_name_plural': 'القروض',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_salary', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='الراتب الأساسي')),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='بدل السكن')),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='بدل النقل')),
                ('food_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='بدل الطعام')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='ساعات الإضافي')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='مبلغ الإضافي')),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المكافأة')),
                ('commission', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='العمولة')),
                ('deductions_gosi', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='خصم التأمينات الاجتماعية (GOSI)')),
                ('deductions_tax', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='خصم الضريبة')),
                ('deductions_absence', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='خصم الغياب')),
                ('deductions_loan', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='خصم القروض')),
                ('deductions_other', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='خصومات أخرى')),
                ('deductions_other_description', models.CharField(blank=True, default='', max_length=200, verbose_name='وصف الخصومات الأخرى')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الاستحقاقات')),
                ('total_deductions_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='إجمالي الخصومات')),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='صافي الراتب')),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'تحويل بنكي'), ('cash', 'نقدي'), ('cheque', 'شيك')], default='bank_transfer', max_length=20, verbose_name='طريقة الدفع')),
                ('payment_status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('paid', 'مدفوع'), ('partially_paid', 'مدفوع جزئياً')], db_index=True, default='pending', max_length=20, verbose_name='حالة الدفع')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الدفع')),
                ('bank_reference', models.CharField(blank=True, default='', max_length=100, verbose_name='المرجع البنكي')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_records_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='hr.employee', verbose_name='الموظف')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='payroll.payrollperiod', verbose_name='الفترة')),
            ],
            options={
                'verbose_name': 'سجل الراتب',
                'verbose_name_plural': 'سجلات الرواتب',
                'ordering': ['employee__first_name'],
                'unique_together': {('period', 'employee')},
            },
        ),
    ]
