# Generated by Django 6.0.4 on 2026-05-01 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_attendance_unique_together_and_more'),
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payrollrecord',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='payrollrecord',
            constraint=models.UniqueConstraint(fields=('period', 'employee'), name='unique_payroll_record_period_employee'),
        ),
    ]
