# Generated by Django 4.2.30 on 2026-04-18 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_alter_journalentry_entry_date'),
        ('hr', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('fiscal_year', models.IntegerField(verbose_name='السنة المالية')),
                ('total_budget', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='إجمالي الميزانية')),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المستخدم')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المتبقي')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمدة'), ('active', 'نشطة'), ('closed', 'مغلقة')], db_index=True, default='draft', max_length=20, verbose_name='الحالة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'ميزانية',
                'verbose_name_plural': 'الميزانيات',
                'ordering': ['-fiscal_year', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='الاسم')),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المخصص')),
                ('utilized_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المستخدم')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ المتبقي')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.account', verbose_name='الحساب')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='budget.budget', verbose_name='الميزانية')),
            ],
            options={
                'verbose_name': 'فئة الميزانية',
                'verbose_name_plural': 'فئات الميزانية',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('from_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_out', to='budget.budget', verbose_name='من ميزانية')),
                ('to_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers_in', to='budget.budget', verbose_name='إلى ميزانية')),
            ],
            options={
                'verbose_name': 'تحويل ميزانية',
                'verbose_name_plural': 'تحويلات الميزانية',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('planned_amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ المخطط')),
                ('actual_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='المبلغ الفعلي')),
                ('status', models.CharField(choices=[('under_budget', 'أقل من الميزانية'), ('on_track', 'على المسار'), ('over_budget', 'أكثر من الميزانية')], db_index=True, default='on_track', max_length=20, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budgetcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'بند الميزانية',
                'verbose_name_plural': 'بنود الميزانية',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='BudgetExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='المبلغ')),
                ('description', models.CharField(max_length=500, verbose_name='الوصف')),
                ('expense_date', models.DateField(verbose_name='تاريخ المصروف')),
                ('reference_number', models.CharField(blank=True, default='', max_length=100, verbose_name='رقم المرجع')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليها'), ('rejected', 'مرفوضة')], db_index=True, default='pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='budget.budget', verbose_name='الميزانية')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='budget.budgetcategory', verbose_name='الفئة')),
            ],
            options={
                'verbose_name': 'مصروف الميزانية',
                'verbose_name_plural': 'مصروفات الميزانية',
                'ordering': ['-created_at'],
            },
        ),
    ]
