# Generated by Django 4.2.30 on 2026-04-28 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='الملف')),
                ('file_name', models.CharField(max_length=255, verbose_name='اسم الملف')),
                ('file_type', models.CharField(max_length=50, verbose_name='نوع الملف')),
                ('file_size', models.PositiveBigIntegerField(default=0, verbose_name='حجم الملف')),
                ('object_id', models.PositiveIntegerField(db_index=True, verbose_name='معرف الكائن')),
                ('description', models.TextField(blank=True, default='', verbose_name='الوصف')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='الفئة')),
                ('is_public', models.BooleanField(default=False, verbose_name='عام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع الكائن')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'مرفق',
                'verbose_name_plural': 'المرفقات',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='attachments_content_44d952_idx'), models.Index(fields=['file_type'], name='attachments_file_ty_cc8c38_idx'), models.Index(fields=['created_at'], name='attachments_created_722260_idx')],
            },
        ),
    ]
