# Generated by Django 4.2.30 on 2026-04-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('warehouse', 'موظف المخازن'), ('sales', 'موظف المبيعات'), ('accountant', 'المحاسب'), ('hr', 'موظف الموارد البشرية'), ('purchasing', 'موظف المشتريات'), ('project_manager', 'مدير المشاريع')], default='sales', max_length=20, verbose_name='الدور الوظيفي'),
        ),
    ]
