# Generated by Django 4.2.30 on 2026-04-13 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('inventory', 'إدارة المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('documents', 'المستندات'), ('projects', 'المشاريع'), ('notifications', 'الإشعارات'), ('auditlog', 'سجل التدقيق'), ('users', 'إدارة المستخدمين'), ('reports', 'التقارير'), ('backup', 'النسخ الاحتياطي'), ('permissions', 'إدارة الصلاحيات')], db_index=True, max_length=30, verbose_name='الوحدة')),
                ('action', models.CharField(choices=[('view', 'عرض'), ('create', 'إنشاء'), ('edit', 'تعديل'), ('delete', 'حذف'), ('export', 'تصدير'), ('approve', 'اعتماد'), ('manage', 'إدارة كاملة')], db_index=True, max_length=15, verbose_name='الإجراء')),
                ('code', models.CharField(db_index=True, max_length=60, unique=True, verbose_name='رمز الصلاحية')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'صلاحية',
                'verbose_name_plural': 'الصلاحيات',
                'ordering': ['module', 'action'],
                'unique_together': {('module', 'action')},
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='المفتاح')),
                ('value', models.TextField(blank=True, default='', verbose_name='القيمة')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='الوصف')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'إعداد نظام',
                'verbose_name_plural': 'إعدادات النظام',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP آخر تسجيل دخول'),
        ),
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, verbose_name='يجب تغيير كلمة المرور'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ آخر تغيير لكلمة المرور'),
        ),
        migrations.AddField(
            model_name='user',
            name='password_history',
            field=models.JSONField(blank=True, default=list, verbose_name='سجل كلمات المرور السابقة'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='مفتاح TOTP'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_backup_codes',
            field=models.JSONField(blank=True, default=list, verbose_name='رموز الاسترداد'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, verbose_name='المصادقة الثنائية مفعّلة'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('warehouse', 'موظف المخازن'), ('sales', 'موظف المبيعات'), ('accountant', 'المحاسب'), ('hr', 'موظف الموارد البشرية'), ('purchasing', 'موظف المشتريات'), ('project_manager', 'مدير المشاريع')], db_index=True, max_length=20, verbose_name='الدور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission', verbose_name='الصلاحية')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'ordering': ['role'],
                'unique_together': {('role', 'permission')},
            },
        ),
    ]
