# Generated by Django 4.2.30 on 2026-04-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_permission_systemsetting_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('inventory', 'إدارة المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('documents', 'المستندات'), ('projects', 'المشاريع'), ('notifications', 'الإشعارات'), ('auditlog', 'سجل التدقيق'), ('users', 'إدارة المستخدمين'), ('reports', 'التقارير'), ('backup', 'النسخ الاحتياطي'), ('permissions', 'إدارة الصلاحيات'), ('pos', 'نقاط البيع'), ('invoicing', 'الفواتير'), ('payroll', 'الرواتب والأجور'), ('warehouse', 'المستودعات'), ('assets', 'الأصول الثابتة'), ('contracts', 'العقود'), ('payments', 'المدفوعات'), ('videos', 'الفيديوهات التعليمية')], db_index=True, max_length=30, verbose_name='الوحدة'),
        ),
    ]
