# Generated by Django 4.2.30 on 2026-04-28 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_permission_module'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('role', models.CharField(choices=[('admin', 'مدير النظام'), ('warehouse', 'موظف المخازن'), ('sales', 'موظف المبيعات'), ('accountant', 'المحاسب'), ('hr', 'موظف الموارد البشرية'), ('purchasing', 'موظف المشتريات'), ('project_manager', 'مدير المشاريع')], max_length=20, verbose_name='الدور')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='الاسم الأخير')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='رمز الدعوة')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('accepted', 'مقبولة'), ('expired', 'منتهية الصلاحية'), ('cancelled', 'ملغاة')], db_index=True, default='pending', max_length=10, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ القبول')),
                ('expires_at', models.DateTimeField(verbose_name='تاريخ انتهاء الصلاحية')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='أُرسلت بواسطة')),
            ],
            options={
                'verbose_name': 'دعوة',
                'verbose_name_plural': 'الدعوات',
                'ordering': ['-created_at'],
            },
        ),
    ]
