# Generated by Django 6.0.4 on 2026-05-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'مدير النظام'), ('warehouse', 'موظف المخازن'), ('sales', 'موظف المبيعات'), ('accountant', 'المحاسب'), ('hr', 'موظف الموارد البشرية'), ('purchasing', 'موظف المشتريات'), ('project_manager', 'مدير المشاريع')], db_index=True, default='sales', max_length=20, verbose_name='الدور الوظيفي'),
        ),
    ]
