# Generated by Django 6.0.4 on 2026-05-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='رقم الهاتف'),
        ),
    ]
