# Generated by Django 4.2.30 on 2026-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, verbose_name='محاولات تسجيل الدخول الفاشلة'),
        ),
        migrations.AddField(
            model_name='user',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='مقفل حتى'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('dashboard', 'لوحة التحكم'), ('inventory', 'إدارة المخزون'), ('sales', 'المبيعات'), ('purchases', 'المشتريات'), ('accounting', 'المحاسبة'), ('hr', 'الموارد البشرية'), ('documents', 'المستندات'), ('projects', 'المشاريع'), ('notifications', 'الإشعارات'), ('auditlog', 'سجل التدقيق'), ('users', 'إدارة المستخدمين'), ('reports', 'التقارير'), ('backup', 'النسخ الاحتياطي'), ('permissions', 'إدارة الصلاحيات'), ('pos', 'نقاط البيع'), ('invoicing', 'الفواتير'), ('payroll', 'الرواتب والأجور'), ('warehouse', 'المستودعات'), ('payments', 'المدفوعات'), ('videos', 'الفيديوهات التعليمية')], db_index=True, max_length=30, verbose_name='الوحدة'),
        ),
    ]
